src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>QuickBooks_Id__c</fullName>
        <externalId>true</externalId>
        <label>QuickBooks Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Error_Log__c.object
<CustomObject>
    <description>Log errors discovered during QBO calls and allocates against the relevant object (eg account, batch, order)</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Batch_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Batch Jobs</label>
        <referenceTo>Batch_Jobs__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuickBooksId__c</fullName>
        <externalId>true</externalId>
        <label>QuickBooksId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <description>The office total to be used . Replaces order amount as it factors in the opp uplift factor and the the stall multipliers</description>
        <inlineHelpText>The grand total for the order</inlineHelpText>
        <label>Total</label>
        <summarizedField>OrderItem.Total__c</summarizedField>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The date the order items was for</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Formula_Total__c</fullName>
        <formula>UnitPrice  * 
Quantity * 
CASE( PricebookEntry.Product2.ProductCode , 
   &apos;Monday&apos;, BLANKVALUE(Stall__r.MondayMultiplier__c,1), 
   &apos;Tuesday&apos;, BLANKVALUE(Stall__r.TuesdayMultiplier__c,1) , 
   &apos;Wednesday&apos;, BLANKVALUE(Stall__r.WednesdayMultiplier__c,1) , 
   &apos;Thursday&apos;, BLANKVALUE(Stall__r.ThursdayMultiplier__c,1), 
   &apos;Friday&apos;, BLANKVALUE(Stall__r.FridayMultiplier__c,1), 
   &apos;Saturday&apos;, BLANKVALUE(Stall__r.SaturdayMultiplier__c,1), 
   &apos;Sunday&apos;, BLANKVALUE(Stall__r.SundayMultiplier__c,1),1) *   BLANKVALUE(Order.Opportunity.Uplift_Factor__c, 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formula Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>QuickBooksId__c</fullName>
        <externalId>true</externalId>
        <label>QuickBooksId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stall</label>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <defaultValue>0</defaultValue>
        <description>To be used instead of  Total Price for the total line price</description>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Sku__c</fullName>
        <formula>BLANKVALUE(Sku_Override__c , Product2.SKU__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sku</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/POBuilder.cls
global class POBuilder {

    @future  (callout=true)
    Webservice static void GeneratePurchaseOrder(Id orderId)
    {

        List<Order> orders = [SELECT Account.QuickBooks_Id__c,Batch_Job__c,Description,EffectiveDate
                       		,EndDate,Id,OpportunityId,OrderNumber,QuickBooksId__c,Status,StatusCode , 
                        	(SELECT Date__c,Description,Formula_Total__c,ListPrice,OrderItemNumber
                             	,Quantity,ServiceDate,Total__c,UnitPrice,Stall__r.Name, PricebookEntry.Sku__c
                        	 FROM OrderItems)
                       FROM Order 
                       WHERE Id = :orderId];

        GeneratePurchaseOrders(orders);
    }
    
    public static boolean GeneratePurchaseOrders(List<Order> orders)
    {
        QBOCRUDHelper qbo = new QBOCRUDHelper();
        //create map of quick books products to map against the salesforce products by Sku Id
        QBOProductList products = QBOProductList.getInstance();
        Map<string, QBOProductList.Item >  productMap = new Map<string, QBOProductList.Item  >(); 
        for (QBOProductList.Item item : products.QueryResponse.Item)
        {
            productMap.put(item.Sku, item);  
        }
        system.debug('productMap: ' + productMap);
        
        List<Order> ordersToUpdate = new List<Order>();
        List<Error_Log__c> errorLogsToInsert = new List<Error_Log__c>();
        for (Order order : orders)
        {
            try
            {
                QBOPurchaseOrderResponse.PurchaseOrder po = new  QBOPurchaseOrderResponse.PurchaseOrder();
                QBOPurchaseOrderResponse.Reference vendorRef = new QBOPurchaseOrderResponse.Reference();
                vendorRef.value = order.Account.QuickBooks_Id__c;
                po.VendorRef = vendorRef;
                po.Memo = order.Description;
                po.GlobalTaxCalculation = 'TaxInclusive';

                po.TxnDate = ((DateTime)order.EffectiveDate).format('YYYY-MM-dd');
                po.DocNumber = order.OrderNumber;
                
                List<QBOPurchaseOrderResponse.Line> invLines = new List<QBOPurchaseOrderResponse.Line>();
                for(OrderItem oi : order.OrderItems)
                {
                   
                    QBOPurchaseOrderResponse.Line line = new QBOPurchaseOrderResponse.Line();
                    line.Amount = oi.UnitPrice * oi.Quantity / 1.1;
                    line.Description = '';
                    
                    if (oi.Description != null)
                    {
                        line.Description += oi.Description;  
                    }
                     
                    line.DetailType = 'ItemBasedExpenseLineDetail';
                    QBOPurchaseOrderResponse.ItemBasedExpenseLineDetail lineDetail = new QBOPurchaseOrderResponse.ItemBasedExpenseLineDetail();

                    lineDetail.UnitPrice = oi.UnitPrice;
                    lineDetail.Qty = oi.Quantity;  
                    
                    QBOProductList.Item item = productMap.get(oi.PricebookEntry.Sku__c);
                    string taxCodeRefValue = '10';// defaults to handle unmapped senarios 10 is GST 
                    string itemRefValue = '1';  // defaults to handle unmapped senarios 1 is SERVCICE 
                    
                    if (item != null)
                    {
                        itemRefValue = item.Id;
                        if (item.PurchaseTaxCodeRef != null)
                        {
                            taxCodeRefValue = item.PurchaseTaxCodeRef.value;
                        }
                    }
                    
                    QBOPurchaseOrderResponse.TaxCodeRef taxCodeRef = new QBOPurchaseOrderResponse.TaxCodeRef();
                    taxCodeRef.value = taxCodeRefValue;
                    lineDetail.TaxCodeRef = taxCodeRef;
                    QBOPurchaseOrderResponse.Reference itemRef  = new QBOPurchaseOrderResponse.Reference();
                    itemRef.value = itemRefValue;
                    lineDetail.ItemRef = itemRef;
                    line.ItemBasedExpenseLineDetail = lineDetail;
                    
                    invLines.add(line);
                    
                    
                }
                po.Line = invLines;
                
                System.debug('Creating PO : ' + system.JSON.serialize(po, true));
                
                
                object response = qbo.upsertData('purchaseorder', system.JSON.serialize(po, true), QBOPurchaseOrderResponse.class);
                QBOPurchaseOrderResponse poResponse;
                if (response instanceof QBOError){
                    //log the error and move to next account
                    errorLogsToInsert.addAll( ErrorLogHelper.LogOrderError(order, (QBOError)response));
                    order.Status = 'Error';
                    ordersToUpdate.add(order);
                    continue;
                }else{
                    poResponse = (QBOPurchaseOrderResponse)response;
                    order.QuickBooksId__c = poResponse.PurchaseOrder.Id;
                    order.Status = 'Activated';
                }                  
            }
            catch(Exception ex)
            {
                errorLogsToInsert.add(ErrorLogHelper.LogOrderError(order, ex));
                order.Status = 'Error';
                
            }
            ordersToUpdate.add(order);

        }
        Insert errorLogsToInsert;// insert any errors
		update ordersToUpdate;   // updatethe orders with the qboId
        return true;
    }
}