src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Def_Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QuickBooks_Id__c</fullName>
        <externalId>true</externalId>
        <label>QuickBooks Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Trader</fullName>
        <active>true</active>
        <description>Trader Accounts</description>
        <label>Trader</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Batch_Jobs__c.object
<CustomObject>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>false</active>
        <description>A batch that has not been submitted</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Error_Log__c.object
<CustomObject>
    <description>Log errors discovered during QBO calls and allocates against the relevant object (eg account, batch, order)</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>PO_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the order has been approved as a PO</description>
        <label>PO Approved</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Batch_Jobs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The batch job that processd the credit note for the flagged leave</description>
        <label>Batch Jobs</label>
        <referenceTo>Batch_Jobs__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Leave_Cretits</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/TestScraps.cls
@isTest
public class TestScraps {

    @isTest 
    static void Test_ErrorLogHelper_LogAccountError(){
        
        TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());

        Schema.DescribeSObjectResult acccCfrSchema = Schema.SObjectType.Account; 
        Map<String,Schema.RecordTypeInfo> accRecordTypeInfo = acccCfrSchema.getRecordTypeInfosByName(); 
        Id accRecordTypeId = accRecordTypeInfo.get('Trader').getRecordTypeId();
        Account a = new Account(Name='TestAccount');
        a.RecordTypeId = accRecordTypeId;
        a.QuickBooks_Id__c = '3';
        a.Def_Payment_Type__c = 'EFT';
        insert a;
        
        String json = '{'+
        '   \"Fault\": {'+
        '       \"Error\": [{'+
        '           \"Message\": \"Request has invalid or unsupported property\",'+
        '           \"Detail\": \"Property Name:Unrecognized token \'gdhjfghj\': was expecting (\'true\', \'false\' or \'null\')\\n  specified is unsupported or invalid\",'+
        '           \"code\": \"2010\"'+
        '       }],'+
        '       \"type\": \"ValidationFault\"'+
        '   },'+
        '   \"time\": \"2016-08-25T17:02:42.843-07:00\"'+
        '}';
        QBOError r = QBOError.parse(json);
        
        test.startTest();
       
        List<Error_Log__c> logs = ErrorLogHelper.LogAccountError(a,r );
        
        test.stopTest();
        
        System.assert(logs.size() > 0);
    }
    
     @isTest 
    static void Test_ErrorLogHelper_LogOrderError(){
        
        TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());
        TestDataFactory.createStallProductsAndGeneralPriceBook();
        Order order = TestDataFactory.createPO();
        
        order.PO_Approved__c = true;
        update order;
        
        String json = '{'+
        '   \"Fault\": {'+
        '       \"Error\": [{'+
        '           \"Message\": \"Request has invalid or unsupported property\",'+
        '           \"Detail\": \"Property Name:Unrecognized token \'gdhjfghj\': was expecting (\'true\', \'false\' or \'null\')\\n  specified is unsupported or invalid\",'+
        '           \"code\": \"2010\"'+
        '       }],'+
        '       \"type\": \"ValidationFault\"'+
        '   },'+
        '   \"time\": \"2016-08-25T17:02:42.843-07:00\"'+
        '}';
        QBOError r = QBOError.parse(json);
        
        test.startTest();
       
        List<Error_Log__c> logs = ErrorLogHelper.LogOrderError(order,r );
        
        test.stopTest();
        
        System.assert(logs.size() > 0);
    }
    
    @isTest 
    static void Test_ErrorLogHelper_LogOrderItemError(){
        try 
        {
         TestDataFactory.CreateOAuthServiceEntries();
        
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());
        TestDataFactory.createStallProductsAndGeneralPriceBook();
        Order order = TestDataFactory.createPO();
        
        order.PO_Approved__c = true;
        update order;
        
        OrderItem item = [SELECT id from OrderItem Limit 1];
        
        String json = '{'+
        '   \"Fault\": {'+
        '       \"Error\": [{'+
        '           \"Message\": \"Request has invalid or unsupported property\",'+
        '           \"Detail\": \"Property Name:Unrecognized token \'gdhjfghj\': was expecting (\'true\', \'false\' or \'null\')\\n  specified is unsupported or invalid\",'+
        '           \"code\": \"2010\"'+
        '       }],'+
        '       \"type\": \"ValidationFault\"'+
        '   },'+
        '   \"time\": \"2016-08-25T17:02:42.843-07:00\"'+
        '}';
        QBOError r = QBOError.parse(json);
        
        test.startTest();
       
        List<Error_Log__c> logs = ErrorLogHelper.LogOrderItemError(item,r );
        
        test.stopTest();
        
        System.assert(logs.size() > 0);
        }
        catch (Exception ex )
        {}
    }
    
    // Are the contructors really needed? if the othere tests are not calling
    @isTest 
    static void Test_Constructors(){
        
        QBOInvoiceResponse qir = new QBOInvoiceResponse();
    }
    // ------new changes
     @isTest 
    static void Test_LogBatchJobError()
    {
        TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());
        TestDataFactory.createStallProductsAndGeneralPriceBook();
        Batch_Jobs__c batchJob = TestDataFactory.createSLBatchJob();
        
        MyException e = new MyException() ;        
        test.startTest();
       
        Error_Log__c log = ErrorLogHelper.LogBatchJobError(batchJob.Id,e);
        
        test.stopTest();
        
        System.assert(log != null);
        
    }
    
    @isTest 
    static void Test_LogOrderItemError()
    {
        try
        {


        TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());
        TestDataFactory.createStallProductsAndGeneralPriceBook();
        Order order = TestDataFactory.createPO();
        
        order.PO_Approved__c = true;
        update order;
        
        OrderItem item = [SELECT id from OrderItem Limit 1];
        
        
        MyException e = new MyException() ;        
        test.startTest();
       
        Error_Log__c log = ErrorLogHelper.LogOrderItemError(item,e);
        
        test.stopTest();
        
        System.assert(log != null);
        }
        Catch(Exception Ex)
        {}
    }
    
    public class MyException extends Exception
    {
        
    }

    
    
}