src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Def_Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QuickBooks_Id__c</fullName>
        <externalId>true</externalId>
        <label>QuickBooks Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Trader</fullName>
        <active>true</active>
        <description>Trader Accounts</description>
        <label>Trader</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Batch_Jobs__c.object
<CustomObject>
    <fields>
        <fullName>Due_Before__c</fullName>
        <label>Due Before</label>
        <type>Date</type>
    </fields>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>false</active>
        <description>A batch that has not been submitted</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>


    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>AccountPayments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Batch_Jobs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Batch Jobs</label>
        <referenceTo>Batch_Jobs__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Reference__c</fullName>
        <label>Customer Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account is the Parent Object and Payment is the child Object</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Batch_Jobs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Payment is the child Object and Batch Job is the parent object.</description>
        <inlineHelpText>Select related Batch Job</inlineHelpText>
        <label>Batch Jobs</label>
        <referenceTo>Batch_Jobs__c</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Reference__c</fullName>
        <description>Customer Reference details from Quickbook</description>
        <label>Customer Reference</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocNumber__c</fullName>
        <description>DocNumber from Quick book</description>
        <label>DocNumber</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_QuickBookId__c</fullName>
        <description>Payment Id from quick book.</description>
        <externalId>true</externalId>
        <label>Invoice QuickBookId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <description>TotalAmount from Quickbook</description>
        <label>TotalAmount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PaymentBuilderTest.cls
@isTest 
public class PaymentBuilderTest {

	@isTest 
    static void TestProcessTransactions() {
    	TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());

        Schema.DescribeSObjectResult acccCfrSchema = Schema.SObjectType.Account; 
        Map<String,Schema.RecordTypeInfo> accRecordTypeInfo = acccCfrSchema.getRecordTypeInfosByName(); 
        Id accRecordTypeId = accRecordTypeInfo.get('Trader').getRecordTypeId();
        Account a = new Account(Name='TestAccount');
        a.RecordTypeId = accRecordTypeId;
        a.QuickBooks_Id__c = '3';
        a.Def_Payment_Type__c = 'EFT';
        insert a;
        
        Batch_Jobs__c job = TestDataFactory.createSLBatchJob();
        
        job.Due_Before__c = Date.today();
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Batch_Jobs__c; 
        Map<String,Schema.RecordTypeInfo> BatchJobsTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = BatchJobsTypeInfo.get('New Payments').getRecordTypeId();
        job.RecordTypeId = rtId;
        Update job;
        
        PaymentBuilder.UpdateBatchObject(job.Id);
        
        test.startTest();
        
		PaymentBuilder.processTransactions(job.Id);
        
        test.stopTest();
        
        List<Transaction__c> trans = [select id from Transaction__c];
        
        system.assert(trans.size()>0);


    }
    
    @isTest 
    static void TestGeneratePayments() {
    	TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());

        Schema.DescribeSObjectResult acccCfrSchema = Schema.SObjectType.Account; 
        Map<String,Schema.RecordTypeInfo> accRecordTypeInfo = acccCfrSchema.getRecordTypeInfosByName(); 
        Id accRecordTypeId = accRecordTypeInfo.get('Trader').getRecordTypeId();
        Account a = new Account(Name='TestAccount');
        a.RecordTypeId = accRecordTypeId;
        a.QuickBooks_Id__c = '3';
        a.Def_Payment_Type__c = 'EFT';
        insert a;
        
        Batch_Jobs__c job = TestDataFactory.createSLBatchJob();
        
        job.Due_Before__c = Date.today();
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Batch_Jobs__c; 
        Map<String,Schema.RecordTypeInfo> BatchJobsTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = BatchJobsTypeInfo.get('New Payments').getRecordTypeId();
        job.RecordTypeId = rtId;
        Update job;
        
        PaymentBuilder.changeRecordTypegeneratePayments(job.Id);
        
        Transaction__c transInv = new Transaction__c();
        transInv.Account__c = a.Id;
        transInv.Customer_Reference__c = '3';
        transInv.DocNumber__c = '123';
        transInv.TotalAmount__c = 1000;
        transInv.Invoice_QuickBookId__c = '2';
        transInv.Type__c = 'Invoice';
        transInv.Batch_Jobs__c = job.Id; 
        insert transInv;
        
        Transaction__c transInv2 = new Transaction__c();
        transInv2.Account__c = a.Id;
        transInv2.Customer_Reference__c = '3';
        transInv2.TotalAmount__c = 600;
        transInv2.DocNumber__c = '124';
        transInv2.Invoice_QuickBookId__c = '4';
        transInv2.Type__c = 'Invoice';
        transInv2.Batch_Jobs__c = job.Id;
        insert transInv2;     
        
        Transaction__c transCN = new Transaction__c();
        transCN.Account__c = a.Id;
        transCN.Customer_Reference__c = '3';
        transCN.TotalAmount__c = 200;
        transCN.DocNumber__c = '124cn';
        transCN.Invoice_QuickBookId__c = '5';
        transCN.Type__c = 'CreditMemo';
        transCN.Batch_Jobs__c = job.Id;
        insert transCN; 
        
        test.startTest();
        
		PaymentBuilder.generatePayments(job.Id);
        
        test.stopTest();
        
        List<Payment__c> pmt = [select id from Payment__c];
        
        system.assert(pmt.size()>0);


    }
    
    
    
    @isTest 
    static void TestDownloadABAFileController() {
    	TestDataFactory.CreateOAuthServiceEntries();
        TestDataFactory.CreateQvm_ABA_File_Generator();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());

        Schema.DescribeSObjectResult acccCfrSchema = Schema.SObjectType.Account; 
        Map<String,Schema.RecordTypeInfo> accRecordTypeInfo = acccCfrSchema.getRecordTypeInfosByName(); 
        Id accRecordTypeId = accRecordTypeInfo.get('Trader').getRecordTypeId();
        Account a = new Account(Name='TestAccount');
        a.RecordTypeId = accRecordTypeId;
        a.QuickBooks_Id__c = '3';
        a.Def_Payment_Type__c = 'EFT';
        insert a;
        
        Batch_Jobs__c job = TestDataFactory.createSLBatchJob();
        
        job.Due_Before__c = Date.today();
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Batch_Jobs__c; 
        Map<String,Schema.RecordTypeInfo> BatchJobsTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = BatchJobsTypeInfo.get('New Payments').getRecordTypeId();
        job.RecordTypeId = rtId;
        Update job;
        
        PaymentBuilder.changeRecordTypegeneratePayments(job.Id);
        
        Transaction__c transInv = new Transaction__c();
        transInv.Account__c = a.Id;
        transInv.Customer_Reference__c = '3';
        transInv.DocNumber__c = '123';
        transInv.TotalAmount__c = 1000;
        transInv.Invoice_QuickBookId__c = '2';
        transInv.Type__c = 'Invoice';
        transInv.Batch_Jobs__c = job.Id; 
        insert transInv;
        
        Transaction__c transInv2 = new Transaction__c();
        transInv2.Account__c = a.Id;
        transInv2.Customer_Reference__c = '3';
        transInv2.TotalAmount__c = 600;
        transInv2.DocNumber__c = '124';
        transInv2.Invoice_QuickBookId__c = '4';
        transInv2.Type__c = 'Invoice';
        transInv2.Batch_Jobs__c = job.Id;
        insert transInv2;     
        
        Transaction__c transCN = new Transaction__c();
        transCN.Account__c = a.Id;
        transCN.Customer_Reference__c = '3';
        transCN.TotalAmount__c = 200;
        transCN.DocNumber__c = '124cn';
        transCN.Invoice_QuickBookId__c = '5';
        transCN.Type__c = 'CreditMemo';
        transCN.Batch_Jobs__c = job.Id;
        insert transCN; 
        
        test.startTest();
        
		PaymentBuilder.generatePayments(job.Id);
        
        test.stopTest();
        
        
        List<Payment__c> pmt = [select id from Payment__c];
        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(job); 
        DownloadABAFileController pg = new DownloadABAFileController(sc);
        pg.fetch();
        system.assert(pmt.size()>0);


    }
}