src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>QuickBooks_Id__c</fullName>
        <externalId>true</externalId>
        <label>QuickBooks Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Batch_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Batch Jobs</label>
        <referenceTo>Batch_Jobs__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuickBooksId__c</fullName>
        <externalId>true</externalId>
        <label>QuickBooksId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <description>The office total to be used . Replaces order amount as it factors in the opp uplift factor and the the stall multipliers</description>
        <inlineHelpText>The grand total for the order</inlineHelpText>
        <label>Total</label>
        <summarizedField>OrderItem.Total__c</summarizedField>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvoiceBuilder.cls
global class InvoiceBuilder {

    // Used to generate one order into a QBO invoice from the Salesforce UI
    Webservice static boolean GenerateInvoiceFromOrder(Id orderId)
    {
        /*
        SELECT Account.QuickBooks_Id__c,Batch_Job__c,Description,EffectiveDate,EndDate,Id,OpportunityId,OrderNumber,QuickBooksId__c,Status,StatusCode , 
		(SELECT Date__c,Description,Formula_Total__c,ListPrice,OrderItemNumber,Quantity,ServiceDate,Total__c,UnitPrice,
		Stall__r.Name
        FROM OrderItems)
			FROM Order
		*/
        return true;
    }
    
    
    /*static boolean GenerateInvoiceFromOrder(Id orderId)
    {
        
    }*/

}