src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>QuickBooks_Id__c</fullName>
        <externalId>true</externalId>
        <label>QuickBooks Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Batch_Jobs__c.object
<CustomObject>
    <fields>
        <fullName>Account_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Trader</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Batch Jobs</relationshipLabel>
        <relationshipName>Batch_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Batch_Type__c</fullName>
        <description>The type of Licence that will be processed for this batch. Currently there are three types (SL(Monthy), PE (Weekly), LH(Monthy)</description>
        <inlineHelpText>SL = Stall Licence
PE = Pre Existing
LH = Licence Holder</inlineHelpText>
        <label>Batch Type</label>
        <picklist>
            <picklistValues>
                <fullName>SL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 1st Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 2nd Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 3rd Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 4th Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWW Annual Parks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWW Qtr Drainage Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWW Water Usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metered Water $</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <formula>IF ( TEXT(Process_Range__c) = &quot;Month&quot; , DATE(YEAR(Week_Month_Of__c),MONTH(Week_Month_Of__c) ,01),IF (TEXT(Process_Range__c) = &quot;Week&quot;,(Week_Month_Of__c - MOD( Week_Month_Of__c - DATE(1900, 1, 7), 7))+ 1,Week_Month_Of__c) )</formula>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Process_Range__c</fullName>
        <inlineHelpText>Are you processing for a month or a week</inlineHelpText>
        <label>Process Range</label>
        <picklist>
            <controllingField>Batch_Type__c</controllingField>
            <picklistValues>
                <fullName>Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Week</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <formula>IF ( TEXT(Process_Range__c) = &quot;Month&quot; , IF( 
MONTH( Week_Month_Of__c ) = 12, 
DATE( YEAR( Week_Month_Of__c ), 12, 31 ), 
DATE( YEAR( Week_Month_Of__c ), MONTH ( Week_Month_Of__c ) + 1, 1 ) - 1 
), IF(TEXT(Process_Range__c) = &quot;Week&quot;,(Week_Month_Of__c - MOD( Week_Month_Of__c - DATE(1900, 1, 7), 7))+ 7 ,Week_Month_Of__c) )</formula>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Week_Month_Of__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>Any date that falls in the week or month that will be processes</inlineHelpText>
        <label>Week / Month Of</label>
        <type>Date</type>
    </fields>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>Error_Processing_Leave_Credit_Notes</fullName>
        <active>true</active>
        <label>Error Processing Leave Credit Notes</label>
    </recordTypes>
    <recordTypes>
        <fullName>Leave_Credit_Notes_Generated</fullName>
        <active>true</active>
        <label>Leave Credit Notes Generated</label>
    </recordTypes>
    <recordTypes>
        <fullName>New</fullName>
        <active>false</active>
        <description>A batch that has not been submitted</description>
        <label>New</label>
    </recordTypes>
    <recordTypes>
        <fullName>Processing_Leave_Credit_Notes</fullName>
        <active>true</active>
        <label>Processing Leave Credit Notes</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Error_Log__c.object
<CustomObject>
    <description>Log errors discovered during QBO calls and allocates against the relevant object (eg account, batch, order)</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Leave__c.object
<CustomObject>
    <description>The leave requests for a trader</description>
    <label>Leave</label>
    <nameField>
        <displayFormat>L-{000000000}</displayFormat>
        <label>Leave Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>QuickBooksId__c</fullName>
        <externalId>true</externalId>
        <label>QuickBooksId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <description>The office total to be used . Replaces order amount as it factors in the opp uplift factor and the the stall multipliers</description>
        <inlineHelpText>The grand total for the order</inlineHelpText>
        <label>Total</label>
        <summarizedField>OrderItem.Total__c</summarizedField>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Batch_Jobs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The batch job that processd the credit note for the flagged leave</description>
        <label>Batch Jobs</label>
        <referenceTo>Batch_Jobs__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Leave_Cretits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The date the order items was for</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Formula_Total__c</fullName>
        <formula>UnitPrice  * 
Quantity * 
CASE( PricebookEntry.Product2.ProductCode , 
   &apos;Monday&apos;, BLANKVALUE(Stall__r.MondayMultiplier__c,1), 
   &apos;Tuesday&apos;, BLANKVALUE(Stall__r.TuesdayMultiplier__c,1) , 
   &apos;Wednesday&apos;, BLANKVALUE(Stall__r.WednesdayMultiplier__c,1) , 
   &apos;Thursday&apos;, BLANKVALUE(Stall__r.ThursdayMultiplier__c,1), 
   &apos;Friday&apos;, BLANKVALUE(Stall__r.FridayMultiplier__c,1), 
   &apos;Saturday&apos;, BLANKVALUE(Stall__r.SaturdayMultiplier__c,1), 
   &apos;Sunday&apos;, BLANKVALUE(Stall__r.SundayMultiplier__c,1),1) *   BLANKVALUE(Order.Opportunity.Uplift_Factor__c, 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formula Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Leave__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flags if the trader is on leave for this order item. If this is true then the space will be available for casual traders.</description>
        <label>On Leave</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuickBooksId__c</fullName>
        <externalId>true</externalId>
        <label>QuickBooksId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stall</label>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <defaultValue>0</defaultValue>
        <description>To be used instead of  Total Price for the total line price</description>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Sku__c</fullName>
        <formula>BLANKVALUE(Sku_Override__c , Product2.SKU__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sku</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeaveCreditNoteBuilder.cls
global class LeaveCreditNoteBuilder {
    
    Webservice static boolean GenerateLeaveCreditNotes(Id batchJobId)
    {
        // update the batch to processing 
        LeaveCreditNoteBuilder.SetOrderItemRecordType('Processing_Leave_Credit_Notes', batchJobId);
        // get the orders of the batch and batch process them
        List<OrderItem> orderItems = [SELECT Date__c,Description,Formula_Total__c,ListPrice,OrderItemNumber
                               		  ,Quantity,ServiceDate,Total__c,UnitPrice,Stall__r.Name, PricebookEntry.Sku__c,
                                      Order.Account.QuickBooks_Id__c, Status__c , Batch_Jobs__c, QuickBooksId__c
                               		  FROM OrderItem
                               		  WHERE (Batch_Jobs__r.Id = '' or Batch_Jobs__r.Id  = :batchJobId) and QuickBooksId__c ='' and Leave__c = True];
        
        if(orderItems.size()>0){
            System.debug('I have values '+orderItems);
            LeaveCreditNoteBuilderBatch batch = new LeaveCreditNoteBuilderBatch(orderItems,  batchJobId); 
            database.executebatch(batch,35);
        }
        else
        {
            System.debug('I have no values '+orderItems);
            LeaveCreditNoteBuilder.SetOrderItemRecordType('Leave_Credit_Notes_Generated', batchJobId);
        } 
        return true;
    }
    
    
    public static boolean GenerateLeaveCreditNotes(List<OrderItem> orderItems, Id batchJobId)
    {
        QBOCRUDHelper qbo = new QBOCRUDHelper();
        //create map of quick books products to map against the salesforce products by Sku Id
        QBOProductList products = QBOProductList.getInstance();
        Map<string, QBOProductList.Item >  productMap = new Map<string, QBOProductList.Item  >(); 
        for (QBOProductList.Item item : products.QueryResponse.Item)
        {
            productMap.put(item.Sku, item);  
        }
        system.debug('productMap: ' + productMap);
        
        List<OrderItem> orderItemsToUpdate = new List<OrderItem>();
        List<Error_Log__c> errorLogsToInsert = new List<Error_Log__c>();
        for (OrderItem item : orderItems)
        {
            ///
            try
            {
                QBOInvoice invoice = new QBOInvoice();
                QBOInvoice.Reference custRef = new QBOInvoice.Reference();
                custRef.value = item.Order.Account.QuickBooks_Id__c;
                invoice.CustomerRef = custRef;
                invoice.PrivateNote = item.Description;
                invoice.DocNumber = 'LCN--'+item.OrderItemNumber;
                invoice.TxnDate = ((DateTime)Date.today()).format('YYYY-MM-dd');
                
                
                List<QBOInvoice.Line> invLines = new List<QBOInvoice.Line>();
                
                QBOInvoice.Line line = new QBOInvoice.Line();
                line.Amount = item.Total__c;
                line.Description = '';
                if (item.Stall__r != null)
                {
                    line.Description = item.Stall__r.Name + ' ';
                } 
                if (item.Description != null)
                {
                    line.Description += item.Description;  
                }
                
                line.DetailType = 'SalesItemLineDetail';
                QBOInvoice.SalesItemLineDetail lineDetail = new QBOInvoice.SalesItemLineDetail();
                lineDetail.ServiceDate = ((DateTime)item.Date__c).format('YYYY-MM-dd'); 
                // if  oi.Total__c != oi.TotalPrice then this is a SL or PE order
                // Which should only have a qty of 1 per line and a total that is affected by the 
                // uplift and multiplier
      

                lineDetail.UnitPrice = item.Total__c;
                lineDetail.Qty = 1;  
                
                
                QBOProductList.Item product = productMap.get(item.PricebookEntry.Sku__c);
                string taxCodeRefValue = '10';// defaults to handle unmapped senarios 10 is GST 
                string itemRefValue = '1';  // defaults to handle unmapped senarios 1 is SERVCICE 
                
                if (product != null)
                {
                    itemRefValue = product.Id;
                    if (product.SalesTaxCodeRef != null)
                    {
                        taxCodeRefValue = product.SalesTaxCodeRef.value;
                    }
                }
                
                QBOInvoice.TaxCodeRef taxCodeRef = new QBOInvoice.TaxCodeRef();
                taxCodeRef.value = taxCodeRefValue;
                lineDetail.TaxCodeRef = taxCodeRef;
                QBOInvoice.Reference itemRef  = new QBOInvoice.Reference();
                itemRef.value = itemRefValue;
                lineDetail.ItemRef = itemRef;
                line.SalesItemLineDetail = lineDetail;
                
                invLines.add(line);
                    
                    
                
                invoice.Line = invLines;
                
                System.debug('Creating Invoice : ' + system.JSON.serialize(invoice, true));
                
                item.Batch_Jobs__c = batchJobId;
                object response = qbo.upsertData('creditmemo', system.JSON.serialize(invoice, true), QBOCreditMemoResponse.class);
                QBOCreditMemoResponse creditMemoResponse;
                if (response instanceof QBOError){
                    //log the error and move to next account
                    errorLogsToInsert.addAll( ErrorLogHelper.LogOrderItemError(item, (QBOError)response));
                    
                    item.Status__c = 'Error';
                    orderItemsToUpdate.add(item);
                    continue;
                }else{
                    creditMemoResponse = (QBOCreditMemoResponse)response;
                    item.QuickBooksId__c = creditMemoResponse.CreditMemo.Id;
                    item.Status__c = 'Activated';
                }                  
            }
            catch(Exception ex)
            {
                errorLogsToInsert.add(ErrorLogHelper.LogOrderItemError(item, ex));
                item.Status__c = 'Error';
                
            }
            orderItemsToUpdate.add(item);
            
            ///
        }
        Insert errorLogsToInsert;// insert any errors
        if (errorLogsToInsert.size()> 0 )
        {
            LeaveCreditNoteBuilder.SetOrderItemRecordType('Error_Processing_Leave_Credit_Notes', batchJobId);
        }
        else 
        {
            LeaveCreditNoteBuilder.SetOrderItemRecordType('Leave_Credit_Notes_Generated', batchJobId);
        }
        update orderItemsToUpdate;   // updatethe orders with the qboId
        return true;
    }
    
    
    public static void SetOrderItemRecordType(String DeveloperName, Id batchJobId)
    {
        if (batchJobId != null)
        {
            Batch_Jobs__c job = [SELECT Batch_Type__c,From_Date__c,Id,Name,Process_Range__c
                                 ,RecordType.Name,To_Date__c,Week_Month_Of__c 
                                 FROM Batch_Jobs__c 
                                 WHERE Id = :batchJobId LIMIT 1];
            
            RecordType nextStepType = [SELECT DeveloperName,Id,Name,SobjectType FROM RecordType
                                       WHERE SobjectType = 'Batch_Jobs__c' and DeveloperName = :DeveloperName LIMIT 1] ;
            
            job.RecordTypeId = nextStepType.Id;
            
            update job;
        }
        
    }
}