src/objects/Batch_Jobs__c.object
<CustomObject>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>false</active>
        <description>A batch that has not been submitted</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New stall selector, this should be hidden and used for ui of adding a new stall to the opp</description>
        <label>Stall</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Stall__c.RecordType.DeveloperName</field>
                <operation>notContain</operation>
                <value>Perm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>SL</fullName>
        <active>true</active>
        <businessProcess>QVM Account Business Sales Process</businessProcess>
        <description>Stall Hold Licenses record Type for QVM Account Businesses</description>
        <label>SL</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QBOInvoiceOrderWebhook_Test.cls
@isTest
public class QBOInvoiceOrderWebhook_Test {
    
    static testMethod void testPost(){
        RestRequest req = new RestRequest(); 
        req.addHeader('Content-Type', 'application/json');                
        req.requestURI = '/services/apexrest/QBOInvoiceWebhook';
        req.httpMethod = 'POST';
        String JSONMsg = '{"eventNotifications":[{"realmId":"123145821595617","dataChangeEvent":{"entities":[{"name":"Payment","id":"33898","operation":"Create","lastUpdated":"2016-10-03T18:42:04.000Z"},{"name":"Invoice","id":"33876","operation":"Create","lastUpdated":"2016-10-04T05:40:18.000Z"}]}}]}';
        req.requestBody = Blob.valueof(JSONMsg);
        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;
        RestContext.request.addHeader('httpMethod', 'POST');
        System.debug('RestContext.response '+RestContext.request);
        
        TestDataFactory.createStallProductsAndGeneralPriceBook();
        TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());
        List<Account> accounts = TestDataFactory.createAccountsWithOpps(1,1, 'SL');
        Opportunity opp = [select id, name, Stall__c from Opportunity limit 1];
        TestDataFactory.createSingleStall(opp);
        Batch_Jobs__c job = TestDataFactory.createSLBatchJobLCN();
        TestDataFactory.createOrder('SL');
        
        Test.startTest();
        QBOInvoiceOrderWebhook.post();
        Test.stopTest();
    }
}