src/objects/Batch_Jobs__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Type__c</fullName>
        <description>The type of Licence that will be processed for this batch. Currently there are three types (SL(Monthy), PE (Weekly), LH(Monthy)</description>
        <inlineHelpText>SL = Stall Licence
PE = Pre Existing
LH = Licence Holder</inlineHelpText>
        <label>Batch Type</label>
        <picklist>
            <picklistValues>
                <fullName>SL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 1st Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 2nd Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 3rd Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 4th Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWW Annual Parks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWW Qtr Drainage Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWW Water Usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metered Water $</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Before__c</fullName>
        <label>Due Before</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <formula>IF ( TEXT(Process_Range__c) = &quot;Month&quot; , DATE(YEAR(Week_Month_Of__c),MONTH(Week_Month_Of__c) ,01),IF (TEXT(Process_Range__c) = &quot;Week&quot;,(Week_Month_Of__c - MOD( Week_Month_Of__c - DATE(1900, 1, 7), 7))+ 1,Week_Month_Of__c) )</formula>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Process_Range__c</fullName>
        <inlineHelpText>Are you processing for a month or a week</inlineHelpText>
        <label>Process Range</label>
        <picklist>
            <controllingField>Batch_Type__c</controllingField>
            <picklistValues>
                <fullName>Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Week</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <formula>IF ( TEXT(Process_Range__c) = &quot;Month&quot; , IF( 
MONTH( Week_Month_Of__c ) = 12, 
DATE( YEAR( Week_Month_Of__c ), 12, 31 ), 
DATE( YEAR( Week_Month_Of__c ), MONTH ( Week_Month_Of__c ) + 1, 1 ) - 1 
), IF(TEXT(Process_Range__c) = &quot;Week&quot;,(Week_Month_Of__c - MOD( Week_Month_Of__c - DATE(1900, 1, 7), 7))+ 7 ,Week_Month_Of__c) )</formula>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Week_Month_Of__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>Any date that falls in the week or month that will be processes</inlineHelpText>
        <label>Week / Month Of</label>
        <type>Date</type>
    </fields>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>false</active>
        <description>A batch that has not been submitted</description>
        <label>New</label>
    </recordTypes>
    <recordTypes>
        <fullName>Processing_Orders</fullName>
        <active>true</active>
        <label>Processing Orders</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Free_Day__c.object
<CustomObject>


    <description>Holiday or days that we dont want to charge people on</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Free Day</label>
    <nameField>
        <label>Free Days Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Free Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Status__c</fullName>
        <label>Business Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New stall selector, this should be hidden and used for ui of adding a new stall to the opp</description>
        <label>Stall</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Stall__c.RecordType.DeveloperName</field>
                <operation>notContain</operation>
                <value>Perm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>LH</fullName>
        <active>true</active>
        <businessProcess>QVM Account Business Sales Process</businessProcess>
        <description>Lease Hold Record Type for QVM Account Businesses</description>
        <label>LH</label>
    </recordTypes>
    <recordTypes>
        <fullName>PE</fullName>
        <active>true</active>
        <businessProcess>QVM Account Business Sales Process</businessProcess>
        <description>Pre Existing Record Type for Account Business.</description>
        <label>PE</label>
    </recordTypes>
    <recordTypes>
        <fullName>SL</fullName>
        <active>true</active>
        <businessProcess>QVM Account Business Sales Process</businessProcess>
        <description>Stall Hold Licenses record Type for QVM Account Businesses</description>
        <label>SL</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Batch_Jobs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The batch job that processd the credit note for the flagged leave</description>
        <label>Batch Jobs</label>
        <referenceTo>Batch_Jobs__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Leave_Cretits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The date the order items was for</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stall</label>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <fields>
        <fullName>CWW_Annual_Parks__c</fullName>
        <defaultValue>0</defaultValue>
        <label>CWW Annual Parks</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CWW_Qtr_Drainage_Charge__c</fullName>
        <defaultValue>0</defaultValue>
        <label>CWW Qtr Drainage Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CWW_Water_Usage__c</fullName>
        <defaultValue>0</defaultValue>
        <label>CWW Water Usage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FridayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Friday</description>
        <inlineHelpText>The Account Business allocated to this stall on Friday</inlineHelpText>
        <label>Friday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Friday Stalls</relationshipLabel>
        <relationshipName>FridayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Select if this stall is still a valid stall</inlineHelpText>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MCC_1st_Qtr_Ins__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MCC 1st Qtr Ins</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MCC_2nd_Qtr_Ins__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MCC 2nd Qtr Ins</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MCC_3rd_Qtr_Ins__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MCC 3rd Qtr Ins</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MCC_4th_Qtr_Ins__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MCC 4th Qtr Ins</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Metered_Water__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Metered Water $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MondayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Mondays</description>
        <inlineHelpText>The Account Business allocated to this stall on Mondays</inlineHelpText>
        <label>Monday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Monday Stalls</relationshipLabel>
        <relationshipName>MondayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Rent__c</fullName>
        <formula>Annual_Rent__c / 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Monthly Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to determine the mapping to QB</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Permanent Stall</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Stalls</relationshipLabel>
        <relationshipName>Stalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SaturdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Saturday</description>
        <inlineHelpText>The Account Business allocated to this stall on Saturday</inlineHelpText>
        <label>Saturday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Saturday Stalls</relationshipLabel>
        <relationshipName>SaturdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SundayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Sunday</description>
        <inlineHelpText>The Account Business allocated to this stall on Sunday</inlineHelpText>
        <label>Sunday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sunday Stalls</relationshipLabel>
        <relationshipName>SundayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tenant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tenant</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Stalls (Tenant)</relationshipLabel>
        <relationshipName>Perm_Stalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ThursdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Thursday</description>
        <inlineHelpText>The Account Business allocated to this stall on Thursday</inlineHelpText>
        <label>Thursday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Thursday Stalls</relationshipLabel>
        <relationshipName>ThursdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TuesdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Tuesday</description>
        <inlineHelpText>The Account Business allocated to this stall on Tuesday</inlineHelpText>
        <label>Tuesday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tuesday Stalls</relationshipLabel>
        <relationshipName>TuesdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WednesdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Wednesday</description>
        <inlineHelpText>The Account Business allocated to this stall on Wednesday</inlineHelpText>
        <label>Wednesday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Wednesday Stalls</relationshipLabel>
        <relationshipName>WednesdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderBuilder.cls
global with sharing class OrderBuilder {

        //---------------------- Changing Record Type to Finding Transactions record type ----------------------------------------//    
    Webservice static void UpdateBatchType( Id batchJobId )
    {   
         try
         {
            ID findingRecordTypeID = Schema.SObjectType.Batch_Jobs__c.getRecordTypeInfosByName().get('Processing Orders').getRecordTypeId();
         	Batch_Jobs__c batchJobObj = [SELECT id, Due_Before__c  FROM Batch_Jobs__c where id =:batchJobId LIMIT 1];
         	batchJobObj.RecordTypeId =  findingRecordTypeID;
         	update batchJobObj; 
         }
         catch( Exception Ex )
         {
            System.debug('Exception in UpdateBatchType():' + Ex.getMessage());
         }         
    }
    
    Webservice  static boolean GenerateOrders(Id batchJobId)
    {
        //

        system.debug('Processing batchJobId: ' + batchJobId);
        // get current batch job
        Batch_Jobs__c job = [SELECT Batch_Type__c,From_Date__c,Id,Name,Process_Range__c
                            ,RecordType.Name,To_Date__c,Week_Month_Of__c , Description__c
                            FROM Batch_Jobs__c 
                            WHERE Id = :batchJobId LIMIT 1];

        //system.debug('processType: ' + processType);

        // get the Processing_Orders rec type to set batch as
        RecordType nextStepType = [SELECT DeveloperName,Id,Name,SobjectType FROM RecordType
                            WHERE SobjectType = 'Batch_Jobs__c' and DeveloperName = 'Processing_Orders' LIMIT 1] ;
    
        job.RecordTypeId = nextStepType.Id;

        update job;

        // SLs and PEs need leave processed LHs do not
        if (job.Batch_Type__c  == 'SL' || job.Batch_Type__c  == 'PE')
        {
            
            // GET THE record type that  matchs the  batch type
            RecordType processType =  [SELECT DeveloperName,Id,Name,SobjectType FROM RecordType
                            WHERE SobjectType = 'Opportunity' and DeveloperName = :job.Batch_Type__c LIMIT 1];

            // GET THE Opps (acc bus) with a record type that  matchs the  batch type
            List<Opportunity> opps = [select Id, Name, accountid, pricebook2id
                              ,(select id from MondayStalls__r)
                              ,(select id from TuesdayStalls__r)
                              ,(select id from WednesdayStalls__r)
                              ,(select id from ThursdayStalls__r)
                              ,(select id from FridayStalls__r)
                              ,(select id from SaturdayStalls__r)
                              ,(select id from SundayStalls__r)
                              from opportunity
                              where RecordTypeId = :processType.Id
                              and Business_Status__c = 'Open'];
            
            
             System.debug('PPPP processType.Id: ' + processType.Id);
             
             GenerateOrdersFromAllocatedStalls(job.From_Date__c, job.To_Date__c, opps , batchJobId, job.Description__c, processType.Id) ;               
        }
        else if (job.Batch_Type__c  == 'LH' )
        {
            RecordType processType = [SELECT DeveloperName,Id,Name,SobjectType FROM RecordType
                    WHERE SobjectType = 'Opportunity' and DeveloperName = :job.Batch_Type__c LIMIT 1];

            List<Opportunity> opps = [select Id, Name, accountid
                     ,(select id, Monthly_Rent__c, Product__c from Perm_Stalls__r WHERE IsActive__c = TRUE)
                    from opportunity
                    where id IN (select Tenant__c from Stall__c where Tenant__c  != null  AND Monthly_Rent__c  > 0) and
                     Business_Status__c = 'Open'
                    ];

            GenerateOrdersFromAllocatedPermStalls(job.From_Date__c, job.To_Date__c, opps , batchJobId, job.Description__c) ; 
        }   
        else 
        {

            List<Opportunity> opps = [select Id, Name, accountid
                     ,(select id, Monthly_Rent__c,CWW_Annual_Parks__c,CWW_Qtr_Drainage_Charge__c,CWW_Water_Usage__c,MCC_1st_Qtr_Ins__c,MCC_2nd_Qtr_Ins__c,MCC_3rd_Qtr_Ins__c,MCC_4th_Qtr_Ins__c,Metered_Water__c, Product__c from Perm_Stalls__r WHERE IsActive__c = TRUE)
                    from opportunity
                    where id IN (select Tenant__c from Stall__c where Tenant__c  != null) and
                     Business_Status__c = 'Open'
                    ];

            GenerateFeeOrders(job.From_Date__c, job.To_Date__c, opps , batchJobId, job.Description__c, job.Batch_Type__c) ; 
        }   

        return true;
    }


    /* Luke Farbotko 18-Aug-2016 

       Generations order items for PE and SLs , creates i line items for each stall per day in the period range provided

    */
    public static boolean GenerateOrdersFromAllocatedStalls(Date startDate, Date endDate, List<Opportunity> opps, id batchJobId, string description, id processTypeId)
    {
        // GET ALL ACTIVE PRICE BOOK ENTRIES TO USE LATER
        list<PricebookEntry> pricebookEntries = [SELECT  Id,ProductCode,IsActive,Name,Pricebook2Id,Product2Id,UnitPrice,UseStandardPrice 
                                         FROM PricebookEntry
                                         WHERE  IsActive = true];

        // create map of leave to ref here 
        list<Leave__c> leaveEntries = [SELECT Id, Leave_Date__c, Account_Business__c
                                    FROM Leave__c
                                    WHERE   Account_Business__r.RecordTypeId = :processTypeId];
        
        System.debug('PPPP leaveEntries : ' + leaveEntries );
                                    
        map<string, Leave__c> leaveEntriesMap = new map<string, Leave__c>();
        
        for(Leave__c lv: leaveEntries)
        {
            String val = lv.Leave_Date__c + (String)lv.Account_Business__c;
            leaveEntriesMap.put(val,lv);
        } 
        
        system.debug('PPPP  leaveEntriesMap : ' + leaveEntriesMap);
        system.debug('pricebookEntries  : ' + pricebookEntries);                                 

        map<string, PricebookEntry> pricebookEntriesMap =  new map<string, PricebookEntry>();

        for(PricebookEntry pb: pricebookEntries)
        {
            String val = pb.ProductCode + pb.Pricebook2Id;
            pricebookEntriesMap.put(val, pb);
        }    
        system.debug('pricebookEntriesMap  : ' + pricebookEntriesMap);          
            
        List<Order> ordersToCreate = new List<Order>();

        Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>(opps);

        for (Opportunity opp : opps)
        {
            if (opp.MondayStalls__r.size()  > 0 
                || opp.TuesdayStalls__r.size()  > 0
                || opp.WednesdayStalls__r.size()  > 0
                || opp.ThursdayStalls__r.size()  > 0
                || opp.FridayStalls__r.size()  > 0
                || opp.SaturdayStalls__r.size()  > 0
                || opp.SundayStalls__r.size()  > 0
               )
            {
                system.debug('opp stuff' + opp);
                Order order = new Order();
                order.AccountId = opp.AccountId;
                order.OpportunityId = opp.Id;
                order.EffectiveDate = startDate;
                order.EndDate = endDate;
                order.Status = 'Draft';
                order.Description = description;
                order.Pricebook2Id = opp.Pricebook2Id;
                if (batchJobId != null)
                {
                    order.Batch_Job__c =  batchJobId;
                }
                

                ordersToCreate.add(order);
            }
     
        }

        Insert ordersToCreate;

        //Orders orders = [select id from Orders where ] ;
        //List<Free_Day__c> freeDays = [SELECT Date__c FROM Free_Day__c WHERE ];
		//Map<Free_Day__c, Date__c> m = new Map<Free_Day__c, Date__c>([SELECT Date__c FROM Free_Day__c]);
        //List<Free_Day__c> myList=[select Date__c,Name from Free_Day__c];
        
        Map<Date, String> freesMap = new Map<Date, String>();

        for(Free_Day__c freeDay:[select Date__c,Name from Free_Day__c]){
            freesMap.put(freeDay.Date__c, freeDay.Name);
        }

        List<OrderItem> orderItemsToCreate  = new List<OrderItem>();
        For(Order order : ordersToCreate)
        {
            Date dateIndex = startDate;
            while(dateIndex <= endDate)
            {
                if(!freesMap.containsKey(dateIndex))
                {
                
                    String dayOfWeek = ((Datetime)dateIndex).format('EEEE'); 
                    List<Stall__c> stalls;
                    if (dayOfWeek == 'Monday') 
                    {
                        stalls = oppMap.get(order.OpportunityId).MondayStalls__r;
                    }       
                    else if (dayOfWeek == 'Tuesday') 
                    {
                        stalls = oppMap.get(order.OpportunityId).TuesdayStalls__r;
                    }   
                    else if (dayOfWeek == 'Wednesday')
                    {
                        stalls = oppMap.get(order.OpportunityId).WednesdayStalls__r;
                    }   
                    else if (dayOfWeek == 'Thursday')
                    {
                        stalls = oppMap.get(order.OpportunityId).ThursdayStalls__r;
                    }                           
                    else if (dayOfWeek == 'Friday')
                    {
                        stalls = oppMap.get(order.OpportunityId).FridayStalls__r;
                    }       
                    else if (dayOfWeek == 'Saturday')
                    {  
                        stalls = oppMap.get(order.OpportunityId).SaturdayStalls__r;
                    }   
                    else if (dayOfWeek == 'Sunday')
                    {
                        stalls = oppMap.get(order.OpportunityId).SundayStalls__r;
                    }   
    
                    
                    // here we need to handle leave requirments
                    for (Stall__c stall : stalls)
                    {
                        //system.debug('order : ' + order.Id); 
                        //system.debug('opp : ' + oppMap.get(order.OpportunityId));
                        //system.debug('pricebook id : ' + oppMap.get(order.OpportunityId).Pricebook2Id);
                        //system.debug('dayOfWeek : ' + dayOfWeek);
                        //system.debug('PricebookEntryId :' + pricebookEntriesMap.get(dayOfWeek + (String)oppMap.get(order.OpportunityId).Pricebook2Id ).Id); 
                        // create an order line
                        OrderItem ordItm =new OrderItem();
                        // detirmine the key to use to get the prive book entry for this day
                        String val = dayOfWeek + (String)oppMap.get(order.OpportunityId).Pricebook2Id ; 
                        
                        String leaveKey =  dateIndex + (String)order.OpportunityId; 
                        ordItm.Date__c = dateIndex;
                        ordItm.PricebookEntryId = pricebookEntriesMap.get(val).Id;// + (String)oppMap.get(oppMap).Pricebook2Id
                        
                        ordItm.OrderId = order.Id;
                        ordItm.UnitPrice =  pricebookEntriesMap.get(val).UnitPrice;
                        ordItm.Quantity = 1;
                        ordItm.Stall__c = stall.Id;
                        If(leaveEntriesMap.containsKey(leaveKey))
                        ordItm.Leave__c = true;
                        orderItemsToCreate.add(ordItm);
    
                    }
                }
                dateIndex = dateIndex.addDays(1);
            }
            
        }

        OrderBuilderBatch batch = new OrderBuilderBatch(orderItemsToCreate,  batchJobId); 

        database.executebatch(batch,200);

        //Insert orderItemsToCreate;

        return true;

    }


    /*
        Generates orders for the LH perm stalls, 
    */
    public static boolean GenerateOrdersFromAllocatedPermStalls(Date startDate, Date endDate, List<Opportunity> opps, id batchJobId, string description)
    {

        //get the avaliable pricebook entries for perm stall and put in map for looking up by the product id
        Id standardPriceBookId = PriceBookUtils.getStdPricebookId();

        List<PricebookEntry> pricebookEntries = [SELECT  Id,ProductCode,IsActive,Name,Pricebook2Id,Product2Id,UnitPrice,UseStandardPrice 
                                         FROM PricebookEntry
                                         WHERE  IsActive = true and Pricebook2Id = :standardPriceBookId];

        Map<Id , PricebookEntry> pricebookEntriesMap = new Map<Id, PricebookEntry>();


        for (PricebookEntry pricebookEntry : pricebookEntries)
        {
            pricebookEntriesMap.put(pricebookEntry.Product2Id, pricebookEntry);

        }

        // build order headers
        List<Order> ordersToCreate = new List<Order>();

        Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>(opps);

        for (Opportunity opp : opps)
        {
            Order order = new Order();
            order.AccountId = opp.AccountId;
            order.OpportunityId = opp.Id;
            order.EffectiveDate = startDate;
            order.EndDate = endDate;
            order.Status = 'Draft';
            order.Description = description;
            // Perm products can be gathered from the standard pricebook as they will0 have $0 prices
            order.Pricebook2Id =  standardPriceBookId;//'01s28000009tRAS';//opp.Pricebook2Id;
            if (batchJobId != null)
            {
                order.Batch_Job__c =  batchJobId;
            }
            ordersToCreate.add(order);
        }
        Insert ordersToCreate; 

        // build order lines
        List<OrderItem> orderItemsToCreate  = new List<OrderItem>();
        For(Order order : ordersToCreate)
        {
            Opportunity opp  = oppMap.get(order.OpportunityId);
            for (Stall__c stall : opp.Perm_Stalls__r)
            {
                OrderItem ordItm =new OrderItem();
                ordItm.Date__c = startDate;
                ordItm.PricebookEntryId = pricebookEntriesMap.get(stall.Product__c).Id ;// + (String)oppMap.get(oppMap).Pricebook2Id '01up0000000xyDs'
                ordItm.OrderId = order.Id;
                ordItm.UnitPrice =  stall.Monthly_Rent__c;
                ordItm.Quantity = 1;
                ordItm.Stall__c = stall.Id;
                orderItemsToCreate.add(ordItm);
            }

        }
        OrderBuilderBatch batch = new OrderBuilderBatch(orderItemsToCreate,  batchJobId); 

        database.executebatch(batch,150);

        return true;
    }


    /*
        Process the selected fee related to LH traders
    */
    public static boolean GenerateFeeOrders(Date startDate, Date endDate, List<Opportunity> opps, id batchJobId, string description, string fieldName)
    {

        
        QVM_LH_FEE_SETTING__c setting = QVM_LH_FEE_SETTING__c.getValues(fieldName);

        List<Order> ordersToCreate = new List<Order>();

        Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>(opps);

        for (Opportunity opp : opps)
        {


            //workout if the opp has any fees of the passed type if so the create an order 
            Double feeAmount = 0.0;
            for (Stall__c stall : opp.Perm_Stalls__r)
            {
                if(stall.get(setting.Fee_Field__c) != null && (Double)stall.get(setting.Fee_Field__c) > 0 )
                {
                    feeAmount += (Double)stall.get(setting.Fee_Field__c); 
                }
            }
            if (feeAmount > 0 )
            {
                Order order = new Order();
                order.AccountId = opp.AccountId;
                order.OpportunityId = opp.Id;
                order.EffectiveDate = startDate;
                order.EndDate = endDate;
                order.Status = 'Draft';
                order.Description = description;
                // Perm products can be gathered from the standard pricebook as they will0 have $0 prices
                order.Pricebook2Id =  PriceBookUtils.getStdPricebookId();
                if (batchJobId != null)
                {
                    order.Batch_Job__c =  batchJobId;
                }
                ordersToCreate.add(order);
            }
        }

        Insert ordersToCreate; 

        List<OrderItem> orderItemsToCreate  = new List<OrderItem>();
        For(Order order : ordersToCreate)
        {
            Opportunity opp  = oppMap.get(order.OpportunityId);
            for (Stall__c stall : opp.Perm_Stalls__r)
            {
                if (stall.get(setting.Fee_Field__c) != null && (Double)stall.get(setting.Fee_Field__c) > 0 )
                {
                    OrderItem ordItm =new OrderItem();
                    ordItm.Date__c = startDate;
                    ordItm.PricebookEntryId = (Id)setting.PricebookEntryId__c;// + (String)oppMap.get(oppMap).Pricebook2Id '01up0000000xyDs'
                    ordItm.OrderId = order.Id;
                    ordItm.UnitPrice =  (Double)stall.get(setting.Fee_Field__c);
                    ordItm.Quantity = 1;
                    ordItm.Description = fieldName;
                    ordItm.Stall__c = stall.Id;
                    orderItemsToCreate.add(ordItm);
                }
            }

        }
        //Insert orderItemsToCreate;

        OrderBuilderBatch batch = new OrderBuilderBatch(orderItemsToCreate,  batchJobId); 

        database.executebatch(batch,150);

        return true;
    }

}