src/objects/Batch_Jobs__c.object
<CustomObject>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>false</active>
        <description>A batch that has not been submitted</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Error_Log__c.object
<CustomObject>
    <description>Log errors discovered during QBO calls and allocates against the relevant object (eg account, batch, order)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Account_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Order_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Batch_Jobs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The batch job that processd the credit note for the flagged leave</description>
        <label>Batch Jobs</label>
        <referenceTo>Batch_Jobs__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Leave_Cretits</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/ErrorLogHelper.cls
public class ErrorLogHelper {

    // Log account errors
    public static List<Error_Log__c>  LogAccountError(Account account, QBOError errors){
        
        List<Error_Log__c> errorLogs = new List<Error_Log__c>();
        for (QBOError.Error err : errors.Fault.Error){
            Error_Log__c errorLog = new Error_Log__c();
            errorLog.Message__c = err.Message;
            errorLog.Detail__c = err.Detail;
            errorLog.Code__c = err.code;
            errorLog.Type__c = errors.Fault.type_Z;
            errorLog.Account__c = account.Id;
            
            errorLogs.add(errorLog);
        }
        //
        return  errorLogs;
        
    }
    
    // Log Order errors
    public static List<Error_Log__c> LogOrderError(Order order, QBOError errors){
        
        List<Error_Log__c> errorLogs = new List<Error_Log__c>();
        for (QBOError.Error err : errors.Fault.Error){
            Error_Log__c errorLog = new Error_Log__c();
            errorLog.Message__c = err.Message;
            errorLog.Detail__c = err.Detail;
            errorLog.Code__c = err.code;
            errorLog.Type__c = errors.Fault.type_Z;
            errorLog.Order__c = order.Id;
            
            errorLogs.add(errorLog);
        }
        
        return errorLogs;
        
    }
    
    // Log Order errors
    public static List<Error_Log__c> LogOrderItemError(OrderItem orderItem, QBOError errors){
        
        List<Error_Log__c> errorLogs = new List<Error_Log__c>();
        for (QBOError.Error err : errors.Fault.Error){
            Error_Log__c errorLog = new Error_Log__c();
            errorLog.Message__c = err.Message;
            errorLog.Detail__c = err.Detail;
            errorLog.Code__c = err.code;
            errorLog.Type__c = errors.Fault.type_Z;
            errorLog.Order_Item__c = orderItem.Id;
            
            errorLogs.add(errorLog);
        }
        
        return errorLogs;
        
    }
    
    
    public static Error_Log__c LogOrderError(Order order, Exception error){
        
        Error_Log__c errorLog = new Error_Log__c();
        errorLog.Message__c = error.getMessage();
        errorLog.Detail__c = error.getStackTraceString();
        errorLog.Code__c = error.getLineNumber().format();
        errorLog.Type__c = 'SF Exception';
        errorLog.Order__c = order.Id;
       

        return errorLog;
        
    }
    
    public static Error_Log__c LogBatchJobError(ID jobId, Exception error){
        
        Error_Log__c errorLog = new Error_Log__c();
        errorLog.Message__c = error.getMessage();
        errorLog.Detail__c = error.getStackTraceString();
        errorLog.Code__c = error.getLineNumber().format();
        errorLog.Type__c = 'SF Exception';
        errorLog.Batch_Jobs__c = jobId;
       

        return errorLog;
        
    }
    
       // Log OrderItem errors
    public static Error_Log__c LogOrderItemError(OrderItem orderItem, Exception error){
        
        Error_Log__c errorLog = new Error_Log__c();
        errorLog.Message__c = error.getMessage();
        errorLog.Detail__c = error.getStackTraceString();
        errorLog.Code__c = error.getLineNumber().format();
        errorLog.Type__c = 'SF Exception';
        errorLog.Order_Item__c = orderItem.Id;
       

        return errorLog;
        
    }
    
    
    
}