src/objects/Batch_Jobs__c.object
<CustomObject>
    <fields>
        <fullName>Transaction_Count__c</fullName>
        <label>Transaction Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>false</active>
        <description>A batch that has not been submitted</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>


    <fields>
        <fullName>Batch_Jobs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Batch Jobs</label>
        <referenceTo>Batch_Jobs__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentJson__c</fullName>
        <description>Hold the json string of the payment that will be passed to QBO</description>
        <label>PaymentJson</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>QuickBook_Id__c</fullName>
        <label>QuickBook Id</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PaymentBuilderBatch.cls
global class PaymentBuilderBatch implements Database.Batchable<sObject>, Database.AllowsCallouts
{
    List<Payment__c> payments = new List<Payment__c>();
    Id batchJob;
        
    global PaymentBuilderBatch(List<Payment__c> payments_a, ID batchJobId ) 
    {
		payments = payments_a;
        batchJob = batchJobId;
	}
    global List<Payment__c> start( Database.BatchableContext BC ) 
    {
		return payments;
	}
    global void execute(Database.BatchableContext BC, List<Payment__c>   scope) 
    {
        QBOCRUDHelper crudHelper = new QBOCRUDHelper();	
        List<Payment__c> paymentsToUpdate = new List<Payment__c>();
                
        for(Payment__c payment:scope) 
        {
            QBOPaymentResponse paymentResponse;
            Object response = crudHelper.upsertData('payment', payment.PaymentJson__c, QBOPaymentResponse.class)  ;
            
            if (response instanceof QBOError)
            {
                //log the error and move to next account
                system.debug('Opp error :');
                //ErrorLogHelper.LogAccountError(so, (QBOError)response);
                continue;
            }
            else
            {
                paymentResponse = (QBOPaymentResponse)response;
                payment.QuickBook_Id__c = paymentResponse.Payment.Id;
                paymentsToUpdate.add(payment);
            }    
        }
        insert  paymentsToUpdate;
        // loop through the results now to process the payments in qbo
	}
    global void finish(Database.BatchableContext BC)
    {
        // Getting Record Type - Payments Generated.
        ID paymentgeneratedRecordTypeID = Schema.SObjectType.Batch_Jobs__c.getRecordTypeInfosByName().get('Payments Generated').getRecordTypeId();
        
        Batch_Jobs__c batchJobObj = [SELECT id,Transaction_Count__c  FROM Batch_Jobs__c where id =:batchJob LIMIT 1];
         
         if( batchJobObj != null )
         {
            // Changing Record Type Id to Payments Generated.
            batchJobObj.RecordTypeId =  paymentgeneratedRecordTypeID;
            update batchJobObj;
         }
    }

}