src/objects/Batch_Jobs__c.object
<CustomObject>
    <fields>
        <fullName>Balance_Receeded__c</fullName>
        <description>The amount paid by customer</description>
        <inlineHelpText>The amount paid by customer</inlineHelpText>
        <label>Amount Received</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outstanding_Balance__c</fullName>
        <label>Outstanding Balance</label>
        <summarizedField>Transaction__c.Outstanding_Balance__c</summarizedField>
        <summaryForeignKey>Transaction__c.Batch_Jobs__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <inlineHelpText>The total amount that will be paid on the transactions</inlineHelpText>
        <label>Payment Amount</label>
        <summarizedField>Transaction__c.Signed_Balance__c</summarizedField>
        <summaryForeignKey>Transaction__c.Batch_Jobs__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>false</active>
        <description>A batch that has not been submitted</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <description>Balance data from Quick Book.</description>
        <label>Balance</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Batch_Jobs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Payment is the child Object and Batch Job is the parent object.</description>
        <inlineHelpText>Select related Batch Job</inlineHelpText>
        <label>Batch Jobs</label>
        <referenceTo>Batch_Jobs__c</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <description>TotalAmount from Quickbook</description>
        <label>TotalAmount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchJobTriggerTest.cls
@isTest public class BatchJobTriggerTest {
    @isTest 
    static void TestTransactionsAllPaid() {
       
        TestDataFactory.CreateOAuthServiceEntries();
        TestDataFactory.CreateQvm_ABA_File_Generator();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());
        List<Transaction__c> trans = TestDataFactory.createTransactions();
        //1000,600,200
        
        Batch_Jobs__c batchJob = [SELECT Id,Balance_Receeded__c,Payment_Amount__c,Outstanding_Balance__c 
                                  FROM Batch_Jobs__c 
                                  WHERE Id = :trans.get(0).Batch_Jobs__c LIMIT 1];
        
        system.debug('BBB ' + batchJob);
        
        system.assert(batchJob.Payment_Amount__c == 1400);
        
        for(Transaction__c tran: trans){
            system.assert(Math.abs(tran.Outstanding_Balance__c) == Math.abs(tran.Balance__c));
        }
    }
    @isTest 
    static void TestTransactionsPartPaidFullAmountWithCredit() {
       
        TestDataFactory.CreateOAuthServiceEntries();
        TestDataFactory.CreateQvm_ABA_File_Generator();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());
        List<Transaction__c> trans = TestDataFactory.createTransactions();
        //1000,600,200
        
        Batch_Jobs__c batchJob = [SELECT Id,Balance_Receeded__c,Payment_Amount__c,Outstanding_Balance__c 
                                  FROM Batch_Jobs__c 
                                  WHERE Id = :trans.get(0).Batch_Jobs__c LIMIT 1];
        batchJob.Balance_Receeded__c = 800;
        update(batchJob);
        
        system.debug('BBB ' + batchJob);
        
        List<Transaction__c> transactions = [SELECT Id,Balance__c,TotalAmount__c,Outstanding_Balance__c 
                                  FROM Transaction__c 
                                  WHERE Batch_Jobs__c = :trans.get(0).Batch_Jobs__c];
        
        	//first transaction is 1000 - 800 - 200(C)
            system.assert(transactions.get(0).Balance__c == 1000);
            //system.assert(transactions.get(1).Balance__c == 0);
        	//credit transaction doesnt matter
            //system.assert(Math.abs(transactions.get(2).Balance__c) == 200);
    }
    
    @isTest 
    static void TestTransactionsPartPaidPartAmountWithCredit() {
       
        TestDataFactory.CreateOAuthServiceEntries();
        TestDataFactory.CreateQvm_ABA_File_Generator();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());
        List<Transaction__c> trans = TestDataFactory.createTransactions();
        //1000,600,200
        
        Batch_Jobs__c batchJob = [SELECT Id,Balance_Receeded__c,Payment_Amount__c,Outstanding_Balance__c 
                                  FROM Batch_Jobs__c 
                                  WHERE Id = :trans.get(0).Batch_Jobs__c LIMIT 1];
        batchJob.Balance_Receeded__c = 650;
        update(batchJob);
        
        system.debug('BBB ' + batchJob);
        
        List<Transaction__c> transactions = [SELECT Id,Balance__c,TotalAmount__c,Outstanding_Balance__c 
                                  FROM Transaction__c 
                                  WHERE Batch_Jobs__c = :trans.get(0).Batch_Jobs__c];
        
        	//first transaction is 1000 - 800 - 200(C)
            //system.assert(transactions.get(0).Balance__c == 850);
            //system.assert(transactions.get(1).Balance__c == 0);
        	//credit transaction doesnt matter
            //system.assert(Math.abs(transactions.get(2).Balance__c) == 200);
    }
}