src/objects/Batch_Jobs__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Type__c</fullName>
        <description>The type of Licence that will be processed for this batch. Currently there are three types (SL(Monthy), PE (Weekly), LH(Monthy)</description>
        <inlineHelpText>SL = Stall Licence
PE = Pre Existing
LH = Licence Holder</inlineHelpText>
        <label>Batch Type</label>
        <picklist>
            <picklistValues>
                <fullName>SL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 1st Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 2nd Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 3rd Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 4th Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWW Annual Parks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWW Qtr Drainage Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWW Water Usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metered Water $</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_Range__c</fullName>
        <inlineHelpText>Are you processing for a month or a week</inlineHelpText>
        <label>Process Range</label>
        <picklist>
            <controllingField>Batch_Type__c</controllingField>
            <picklistValues>
                <fullName>Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Week</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Week_Month_Of__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>Any date that falls in the week or month that will be processes</inlineHelpText>
        <label>Week / Month Of</label>
        <type>Date</type>
    </fields>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>false</active>
        <description>A batch that has not been submitted</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Status__c</fullName>
        <label>Business Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contracted_Leave__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of days leave the Trader has for the year</description>
        <label>Contracted Leave Weeks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New stall selector, this should be hidden and used for ui of adding a new stall to the opp</description>
        <label>Stall</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Stall__c.RecordType.DeveloperName</field>
                <operation>notContain</operation>
                <value>Perm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>LH</fullName>
        <active>true</active>
        <businessProcess>QVM Account Business Sales Process</businessProcess>
        <description>Lease Hold Record Type for QVM Account Businesses</description>
        <label>LH</label>
    </recordTypes>
    <recordTypes>
        <fullName>SL</fullName>
        <active>true</active>
        <businessProcess>QVM Account Business Sales Process</businessProcess>
        <description>Stall Hold Licenses record Type for QVM Account Businesses</description>
        <label>SL</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/QVM_LH_FEE_SETTING__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Contains settings that will be used for determining the product/gl account associated with licence holder fees such as water, insurance etc...</description>
    <fields>
        <fullName>Fee_Field__c</fullName>
        <description>The name of the field in the stall table that holes the value of the fee</description>
        <label>Fee Field</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PricebookEntryId__c</fullName>
        <description>The PricebookEntryId of the product / price book to be used against the order line. The product will hold QBO PRODUCT mapping which in turn knows the GL Account mapping</description>
        <label>Pricebook Entry Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>QVM LH FEE SETTING</label>
</CustomObject>

src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <fields>
        <fullName>Annual_Rent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Annual Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FridayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Friday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Friday</inlineHelpText>
        <label>Friday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FridayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Friday</description>
        <inlineHelpText>The Account Business allocated to this stall on Friday</inlineHelpText>
        <label>Friday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Friday Stalls</relationshipLabel>
        <relationshipName>FridayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Select if this stall is still a valid stall</inlineHelpText>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MCC_1st_Qtr_Ins__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MCC 1st Qtr Ins</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MondayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Mondays</description>
        <inlineHelpText>The Account Business allocated to this stall on Mondays</inlineHelpText>
        <label>Monday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Monday Stalls</relationshipLabel>
        <relationshipName>MondayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to determine the mapping to QB</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Permanent Stall</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Stalls</relationshipLabel>
        <relationshipName>Stalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SaturdayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Saturday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Saturday</inlineHelpText>
        <label>Saturday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SaturdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Saturday</description>
        <inlineHelpText>The Account Business allocated to this stall on Saturday</inlineHelpText>
        <label>Saturday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Saturday Stalls</relationshipLabel>
        <relationshipName>SaturdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShedId__c</fullName>
        <label>Shed Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StallId__c</fullName>
        <label>Stall Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SundayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Sunday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Sunday</inlineHelpText>
        <label>Sunday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SundayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Sunday</description>
        <inlineHelpText>The Account Business allocated to this stall on Sunday</inlineHelpText>
        <label>Sunday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sunday Stalls</relationshipLabel>
        <relationshipName>SundayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tenant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tenant</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Stalls (Tenant)</relationshipLabel>
        <relationshipName>Perm_Stalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ThursdayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Thursday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Thursday</inlineHelpText>
        <label>Thursday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ThursdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Thursday</description>
        <inlineHelpText>The Account Business allocated to this stall on Thursday</inlineHelpText>
        <label>Thursday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Thursday Stalls</relationshipLabel>
        <relationshipName>ThursdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TuesdayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Tuesday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Tuesday</inlineHelpText>
        <label>Tuesday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TuesdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Tuesday</description>
        <inlineHelpText>The Account Business allocated to this stall on Tuesday</inlineHelpText>
        <label>Tuesday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tuesday Stalls</relationshipLabel>
        <relationshipName>TuesdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WednesdayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Wednesday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Wednesday</inlineHelpText>
        <label>Wednesday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WednesdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Wednesday</description>
        <inlineHelpText>The Account Business allocated to this stall on Wednesday</inlineHelpText>
        <label>Wednesday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Wednesday Stalls</relationshipLabel>
        <relationshipName>WednesdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <recordTypes>
        <fullName>Casual</fullName>
        <active>true</active>
        <description>Stall locations that can change trader on a day to day basis</description>
        <label>Casual</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permanent</fullName>
        <active>true</active>
        <description>Permanent stall locationc</description>
        <label>Permanent</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    

    public static List<Account> createAccountsWithOpps(Integer numAccts, Integer numOppsPerAcct, string recordType ) {

        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Opportunity; 
        Map<String,Schema.RecordTypeInfo> oppRecordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 

        Id oppRecordTypeId = oppRecordTypeInfo.get(recordType).getRecordTypeId();

        List<Account> accts = new List<Account>();
        
        
        Schema.DescribeSObjectResult acccCfrSchema = Schema.SObjectType.Account; 
        Map<String,Schema.RecordTypeInfo> accRecordTypeInfo = acccCfrSchema.getRecordTypeInfosByName(); 
        Id accRecordTypeId = accRecordTypeInfo.get('Trader').getRecordTypeId();
        
        for(Integer i=0;i<numAccts;i++) {
            Account a = new Account(Name='TestAccount' + i);
            a.RecordTypeId = accRecordTypeId;
            accts.add(a);
        }
        insert accts;
        
        List<Opportunity> opps = new List<Opportunity>();
        for (Integer j=0;j<numAccts;j++) {
            Account acct = accts[j];
            // For each account just inserted, add opportunities
            for (Integer k=0;k<numOppsPerAcct;k++) {
                opps.add(new Opportunity(Name=acct.Name + ' Opportunity ' + k,
                                       RecordTypeid=oppRecordTypeId,
                                       StageName='Prospecting',
                                       CloseDate=System.today().addMonths(1),
                                       AccountId=acct.Id,
                                       Contracted_Leave__c=20,
                                       Business_Status__c = 'Open',
                                       pricebook2id=Test.getStandardPricebookId()));
            }
        }
        // Insert all opportunities for all accounts.
        insert opps;
        
        return accts;
    }

    public static Stall__c createSingleStall(Opportunity accBus)
    {


        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Stall__c; 
        Map<String,Schema.RecordTypeInfo> stallTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = stallTypeInfo.get('Casual').getRecordTypeId();
            
        Stall__c stall = new Stall__c();
        stall.RecordTypeid = rtId;
        stall.ShedId__c = 'A' ;
        stall.StallId__c = '1';

        stall.StallId__c = '1';
        stall.name = 'A1';

        stall.FridayMultiplier__c = 1;
        stall.FridayTrader__c = accBus.Id;
        stall.IsActive__c = true;
        stall.MondayTrader__c = accBus.Id;
        stall.SaturdayMultiplier__c = 1;
        stall.SaturdayTrader__c = accBus.Id;
        stall.SundayMultiplier__c = 1;
        stall.SundayTrader__c = accBus.Id;
        stall.ThursdayMultiplier__c = 1;
        stall.ThursdayTrader__c = accBus.Id;
        stall.TuesdayMultiplier__c = 1;
        stall.TuesdayTrader__c = accBus.Id;
        stall.WednesdayMultiplier__c = 1;
        stall.WednesdayTrader__c = accBus.Id; 

        Insert stall;

        return stall;
    }





    public static Stall__c createSingleStallWithNoOpp()
    {

        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Stall__c; 
        Map<String,Schema.RecordTypeInfo> stallTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = stallTypeInfo.get('Casual').getRecordTypeId();
            


        Stall__c stall = new Stall__c();
        stall.RecordTypeid = rtId;
        stall.ShedId__c = 'A' ;
        stall.StallId__c = '1';

        stall.StallId__c = '1';
        stall.name = 'A1';

        stall.FridayMultiplier__c = 1;
        stall.IsActive__c = true;
        stall.SaturdayMultiplier__c = 1;
        stall.SundayMultiplier__c = 1;
        stall.ThursdayMultiplier__c = 1;
        stall.TuesdayMultiplier__c = 1;
        stall.WednesdayMultiplier__c = 1;

        Insert stall;

        return stall;
    }


    public static Stall__c createPermStallWithNoOpp()
    {

        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Stall__c; 
        Map<String,Schema.RecordTypeInfo> stallTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = stallTypeInfo.get('Permanent').getRecordTypeId();
            


        Stall__c stall = new Stall__c();
        stall.RecordTypeid = rtId;
        stall.ShedId__c = 'X' ;
        stall.StallId__c = '1';

        stall.StallId__c = '1';
        stall.name = 'X1';

        stall.Annual_Rent__c = 12000;

        stall.FridayMultiplier__c = 1;
        stall.IsActive__c = true;
        stall.SaturdayMultiplier__c = 1;
        stall.SundayMultiplier__c = 1;
        stall.ThursdayMultiplier__c = 1;
        stall.TuesdayMultiplier__c = 1;
        stall.WednesdayMultiplier__c = 1;

        Insert stall;

        return stall;
    }

    public static Stall__c createPermStallWithOpp(Opportunity accBus)
    {

        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Stall__c; 
        Map<String,Schema.RecordTypeInfo> stallTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = stallTypeInfo.get('Permanent').getRecordTypeId();
            


        Stall__c stall = new Stall__c();
        stall.RecordTypeid = rtId;
        stall.ShedId__c = 'X' ;
        stall.StallId__c = '1';
        stall.Tenant__c = accBus.Id; 
        stall.StallId__c = '1';
        stall.Product__c = TestDataFactory.createPremStallProducts().Id;
        stall.name = 'X1';

        stall.Annual_Rent__c = 12000;
        stall.MCC_1st_Qtr_Ins__c = 100;

        stall.FridayMultiplier__c = 1;
        stall.IsActive__c = true;
        stall.SaturdayMultiplier__c = 1;
        stall.SundayMultiplier__c = 1;
        stall.ThursdayMultiplier__c = 1;
        stall.TuesdayMultiplier__c = 1;
        stall.WednesdayMultiplier__c = 1;

        Insert stall;

        return stall;
    }




    public static void createStallProductsAndGeneralPriceBook()
    {

            /*PriceBook2 pb = new PriceBook2();
            pb.name = 'General Merchandise';
            pb.isActive=true;
            pb.IsStandard  = true;
            insert pb;*/

            List<Product2> productsToInsert = new List<Product2>();

            Product2 prodMon= new Product2();
            prodMon.name='Monday';
            prodMon.ProductCode='Monday';
            prodMon.isActive=true;
            productsToInsert.add(prodMon);

            Product2 prodTue= new Product2();
            prodTue.name='Tuesday';
            prodTue.ProductCode='Tuesday';
            prodTue.isActive=true;
            productsToInsert.add(prodTue);

            Product2 prodWed= new Product2();
            prodWed.name='Wednesday';
            prodWed.ProductCode='Wednesday';
            prodWed.isActive=true;
            productsToInsert.add(prodWed);

            Product2 prodThu= new Product2();
            prodThu.name='Thursday';
            prodThu.ProductCode='Thursday';
            prodThu.isActive=true;
            productsToInsert.add(prodThu);

            Product2 prodFri= new Product2();
            prodFri.name='Friday';
            prodFri.ProductCode='Friday';
            prodFri.isActive=true;
            productsToInsert.add(prodFri);

            Product2 prodSat = new Product2();
            prodSat.name='Saturday';
            prodSat.ProductCode='Saturday';
            prodSat.isActive=true;
            productsToInsert.add(prodSat);

            Product2 prodSun= new Product2();
            prodSun.name='Sunday';
            prodSun.ProductCode='Sunday';
            prodSun.isActive=true;
            productsToInsert.add(prodSun);

            insert productsToInsert;

            List<PriceBookEntry> pbeToInsert = new List<PriceBookEntry>();

             Id pricebookId = Test.getStandardPricebookId();

            pbeToInsert.add(new PricebookEntry(pricebook2id=pricebookId, product2id=prodMon.id,unitprice=30, isActive=true));
            pbeToInsert.add(new PricebookEntry(pricebook2id=pricebookId, product2id=prodTue.id,unitprice=30, isActive=true));
            pbeToInsert.add(new PricebookEntry(pricebook2id=pricebookId, product2id=prodWed.id,unitprice=30, isActive=true));
            pbeToInsert.add(new PricebookEntry(pricebook2id=pricebookId, product2id=prodThu.id,unitprice=30, isActive=true));
            pbeToInsert.add(new PricebookEntry(pricebook2id=pricebookId, product2id=prodFri.id,unitprice=30, isActive=true));
            pbeToInsert.add(new PricebookEntry(pricebook2id=pricebookId, product2id=prodSat.id,unitprice=30, isActive=true));
            pbeToInsert.add(new PricebookEntry(pricebook2id=pricebookId, product2id=prodSun.id,unitprice=30, isActive=true));

            insert pbeToInsert;

            
    }


    public static Product2 createPremStallProducts()
    {


        

        Product2 prod= new Product2();
        prod.name='perm stall';
        prod.ProductCode='perm stall';
        prod.Family ='Permanent Stall';
        prod.isActive=true;

        insert prod;


        Id pricebookId = Test.getStandardPricebookId();


        PricebookEntry pbe = new PricebookEntry(pricebook2id=pricebookId, product2id=prod.id,unitprice=30, isActive=true);

        insert pbe;

        return prod;

        
    }




    public static Batch_Jobs__c createSLBatchJob()
    {

        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Batch_Jobs__c; 
        Map<String,Schema.RecordTypeInfo> BatchJobsTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = BatchJobsTypeInfo.get('New').getRecordTypeId();
            
        system.debug('TEST : ' + rtId);

        Batch_Jobs__c bj = new Batch_Jobs__c();
        bj.Batch_Type__c = 'SL';
        bj.Process_Range__c = 'Month';
        bj.Week_Month_Of__c = Date.today();
        bj.RecordTypeid = rtId;

        insert bj;

        return bj;
       
    }


    public static Batch_Jobs__c createLHBatchJob()
    {

        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Batch_Jobs__c; 
        Map<String,Schema.RecordTypeInfo> BatchJobsTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = BatchJobsTypeInfo.get('New').getRecordTypeId();
            
        system.debug('TEST : ' + rtId);

        Batch_Jobs__c bj = new Batch_Jobs__c();
        bj.Batch_Type__c = 'LH';
        bj.Process_Range__c = 'Month';
        bj.Week_Month_Of__c = Date.today();
        bj.RecordTypeid = rtId;

        insert bj;

        return bj;
       
    }

    public static Batch_Jobs__c createMCCBatchJob()
    {

        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Batch_Jobs__c; 
        Map<String,Schema.RecordTypeInfo> BatchJobsTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = BatchJobsTypeInfo.get('New').getRecordTypeId();
            
        system.debug('TEST : ' + rtId);

        Batch_Jobs__c bj = new Batch_Jobs__c();
        bj.Batch_Type__c = 'MCC 1st Qtr Ins';
        //bj.Process_Range__c = 'Quarter';
        bj.Week_Month_Of__c = Date.today();
        bj.RecordTypeid = rtId;

        insert bj;

        return bj;
       
    }

    public static void CreateQVM_LH_FEE_SETTING_Entries()
    {

        //CREATE Product and add to standard pricebook
        Product2 prod= new Product2();
        prod.name='a fee';
        prod.ProductCode='fee';
        prod.Family ='Permanent Stall';
        prod.isActive=true;

        insert prod;

        //add to standard pricebook
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbe = new PricebookEntry(pricebook2id=pricebookId, product2id=prod.id,unitprice=0, isActive=true);

        insert pbe;



        //List<QVM_LH_FEE_SETTING__c> settings = new List<QVM_LH_FEE_SETTING__c>();
        QVM_LH_FEE_SETTING__c setting1 = new QVM_LH_FEE_SETTING__c();
        setting1.Name = 'MCC 1st Qtr Ins';
        setting1.Fee_Field__c = 'MCC_1st_Qtr_Ins__c';
        setting1.PricebookEntryId__c = pbe.Id;

        Insert setting1;


    }
    
    
    public static void CreateOAuthServiceEntries()
    {
        OAuthService__c service = new OAuthService__c();
        service.Request_Token_URL__c = 'https://oauth.intuit.com/oauth/v1/get_request_token';
        service.Authorization_URL__c = 'https://appcenter.intuit.com/Connect/Begin';
        service.Access_Token_URL__c = 'https://oauth.intuit.com/oauth/v1/get_access_token';
        service.BaseURL__c = 'https://sandbox-quickbooks.api.intuit.com/v3/company/';
        service.CallbackUrl__c = 'https://cs31.salesforce.com/apex/QuickBooksLogin';
        service.Consumer_Key__c = 'qyprdf5ltQR3fLoNbAq8rVXp2Y3cxK';
        service.Consumer_Secret__c = 'gVblWDndfHuObNQY03aJjUgi7tFqYnQmJzZSsMp3';
        service.Application_Token__c = 'af18d34bbd246b43c3b9781bd831b85be89b';
        service.Name = 'QuickBooksAU';
        
        insert  service;
        OAuth_Token__c oaToken = new OAuth_Token__c();
        oaToken.OAuthService__c = service.Id;
        //oaToken.OAuthService__r.Consumer_Key__c = service.Consumer_Key__c;
        //oaToken.OAuthService__r.Consumer_Secret__c = service.Consumer_Secret__c;
        oaToken.Token__c = 'qyprdf5ltQR3fLoNbAq8rVXp2Y3c';
        oaToken.Secret__c = 'qyprdf5ltQR3fLoNbAq8rVXp2';
        oaToken.Is_Access__c = True;
        oaToken.Realm_Id__c = '67454209';
        
        insert oaToken;
        
    }



}