src/objects/Batch_Jobs__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Type__c</fullName>
        <description>The type of Licence that will be processed for this batch. Currently there are three types (SL(Monthy), PE (Weekly), LH(Monthy)</description>
        <inlineHelpText>SL = Stall Licence
PE = Pre Existing
LH = Licence Holder</inlineHelpText>
        <label>Batch Type</label>
        <picklist>
            <picklistValues>
                <fullName>SL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 1st Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 2nd Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 3rd Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCC 4th Qtr Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWW Annual Parks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWW Qtr Drainage Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWW Water Usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metered Water $</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <formula>IF ( TEXT(Process_Range__c) = &quot;Month&quot; , DATE(YEAR(Week_Month_Of__c),MONTH(Week_Month_Of__c) ,01),IF (TEXT(Process_Range__c) = &quot;Week&quot;,(Week_Month_Of__c - MOD( Week_Month_Of__c - DATE(1900, 1, 7), 7))+ 1,Week_Month_Of__c) )</formula>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Process_Range__c</fullName>
        <inlineHelpText>Are you processing for a month or a week</inlineHelpText>
        <label>Process Range</label>
        <picklist>
            <controllingField>Batch_Type__c</controllingField>
            <picklistValues>
                <fullName>Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Week</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <formula>IF ( TEXT(Process_Range__c) = &quot;Month&quot; , IF( 
MONTH( Week_Month_Of__c ) = 12, 
DATE( YEAR( Week_Month_Of__c ), 12, 31 ), 
DATE( YEAR( Week_Month_Of__c ), MONTH ( Week_Month_Of__c ) + 1, 1 ) - 1 
), IF(TEXT(Process_Range__c) = &quot;Week&quot;,(Week_Month_Of__c - MOD( Week_Month_Of__c - DATE(1900, 1, 7), 7))+ 7 ,Week_Month_Of__c) )</formula>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Week_Month_Of__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>Any date that falls in the week or month that will be processes</inlineHelpText>
        <label>Week / Month Of</label>
        <type>Date</type>
    </fields>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>Orders_Generated</fullName>
        <active>true</active>
        <label>Orders Generated</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Batch_Jobs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The batch job that processd the credit note for the flagged leave</description>
        <label>Batch Jobs</label>
        <referenceTo>Batch_Jobs__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Leave_Cretits</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/OrderBuilderBatch.cls
global class OrderBuilderBatch implements Database.Batchable<sObject> {
	
	List<OrderItem> orderItems;
	Id batchJob;
	
	global OrderBuilderBatch(List<OrderItem> items, Id batchJobId) {
		orderItems = items;
		batchJob = batchJobId;
	}
	
	global List<OrderItem> start(Database.BatchableContext BC) {
		return orderItems;

	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		insert scope;
	}
	
	global void finish(Database.BatchableContext BC) {
			//UPDATE THE BATCH JOB TO 'Orders_Generated'
	 	Batch_Jobs__c job = [SELECT Batch_Type__c,From_Date__c,Id,Name,Process_Range__c
						,RecordType.DeveloperName,To_Date__c,Week_Month_Of__c 
						FROM Batch_Jobs__c 
						WHERE Id = :batchJob LIMIT 1];

		RecordType nextStepType = [SELECT DeveloperName,Id,Name,SobjectType FROM RecordType
						WHERE SobjectType = 'Batch_Jobs__c' and DeveloperName = 'Orders_Generated' LIMIT 1] ;

		job.RecordTypeId = nextStepType.Id;

		update job;
	}
	
}