src/objects/Batch_Jobs__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Qvm_ABA_File_Generator__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Date_to_be_Processed__c</fullName>
        <inlineHelpText>Must be numeric in the formal of DDMMYY. Must be a valid date. Zero filled.</inlineHelpText>
        <label>Date to be Processed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Description of entries on file e.g. &quot;PAYROLL&quot;</inlineHelpText>
        <label>Description</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Institution__c</fullName>
        <description>Name of User&apos;s Financial Institution</description>
        <inlineHelpText>Must be approved Financial Institution abbreviation. Bank of Queensland&apos;s abbreviation is BQL, Westpac&apos;s abbreviation is &quot;WBC&quot;. Consult your Bank for correct abbreviation.</inlineHelpText>
        <label>Financial Institution</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Of_User__c</fullName>
        <description>Name of Use supplying file.</description>
        <inlineHelpText>Must be User Preferred Specification as advised by User&apos;s FI. Left justified, blank filled. All coded character set valid. Must not be all blanks.</inlineHelpText>
        <label>Name Of User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Identification_Number__c</fullName>
        <inlineHelpText>Must be User Identification Number which is allocated by APCA. Must be numeric, right justified, zero filled.</inlineHelpText>
        <label>User Identification Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Qvm ABA File Generator</label>
</CustomObject>

src/classes/DownloadABAFileController.cls
public class DownloadABAFileController
{
    Batch_Jobs__c batchlobObj;
    ID  recId; 
    public Qvm_ABA_File_Generator__c qvmABAFileObj{get;set;}
    
    // Header details
    public string emptyString17 {get ;set;}
    public string emptyString7 {get ;set;}
    public string newLine {get ;set;}
    public string UserName {get ;set;}
    
    
    public DownloadABAFileController( ApexPages.StandardController stdController )
    {        
		batchlobObj = (Batch_Jobs__c)stdController.getRecord();      
        recId = stdController.getRecord().Id;
        
        emptyString17 = ''.rightPad(17);
        emptyString7 = ''.rightPad(7);
        newLine = '\r\n';
    }
    
    public void fetch()
    {
        try
        {
             qvmABAFileObj = [SELECT Financial_Institution__c,Name_Of_User__c,
                             User_Identification_Number__c,Description__c,Date_to_be_Processed__c 
                             FROM Qvm_ABA_File_Generator__c where Name = 'ABA File Header Generator' LIMIT 1]; 
            UserName  =  qvmABAFileObj.Name_Of_User__c;
            UserName = UserName.rightPad(7);
        }
        catch( Exception Ex )
        {
            System.debug('Exception in DownloadABAFileController:fetch():-' + Ex.getMessage());
        }  
    }
    public void FormatStrings()
    {
              
    }
}