src/objects/Batch_Jobs__c.object
<CustomObject>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>false</active>
        <description>A batch that has not been submitted</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New stall selector, this should be hidden and used for ui of adding a new stall to the opp</description>
        <label>Stall</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Stall__c.RecordType.DeveloperName</field>
                <operation>notContain</operation>
                <value>Perm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>SL</fullName>
        <active>true</active>
        <businessProcess>QVM Account Business Sales Process</businessProcess>
        <description>Stall Hold Licenses record Type for QVM Account Businesses</description>
        <label>SL</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Batch_Jobs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The batch job that processd the credit note for the flagged leave</description>
        <label>Batch Jobs</label>
        <referenceTo>Batch_Jobs__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Leave_Cretits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stall</label>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvoiceBuilderTest.cls
@isTest
public class InvoiceBuilderTest {

    @isTest static void TestGenerateOrderAndInvoiceSL() {
        
        TestDataFactory.createStallProductsAndGeneralPriceBook();
        List<Account> accounts = TestDataFactory.createAccountsWithOpps(1,1, 'SL');

        TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());
        

        Opportunity opp = [select id, name, Stall__c from Opportunity limit 1];
        TestDataFactory.createSingleStall(opp);

        Batch_Jobs__c job = TestDataFactory.createSLBatchJob();
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Batch_Jobs__c; 
        Map<String,Schema.RecordTypeInfo> BatchJobsTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = BatchJobsTypeInfo.get('New Orders/Invoices').getRecordTypeId();
            
        system.debug('TEST : ' + rtId);
        
       
        List<OrderItem> oi = TestDataFactory.createOrderItemWithLeave(1,'SL');
		Test.startTest();
     	
       
       	boolean result = InvoiceBuilder.GenerateInvoiceFromOrder(oi[0].OrderId);
    
        Test.stopTest();
        
        system.assert(result == true);
    }
    
    @isTest static void TestGenerateOrdersAndInvoicesSL() {
        
        TestDataFactory.createStallProductsAndGeneralPriceBook();
        List<Account> accounts = TestDataFactory.createAccountsWithOpps(1,1, 'SL');

        TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());
        

        Opportunity opp = [select id, name, Stall__c from Opportunity limit 1];
        TestDataFactory.createSingleStall(opp);

        Batch_Jobs__c job = TestDataFactory.createSLBatchJob();
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Batch_Jobs__c; 
        Map<String,Schema.RecordTypeInfo> BatchJobsTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = BatchJobsTypeInfo.get('New Orders/Invoices').getRecordTypeId();
            
        system.debug('TEST : ' + rtId);
        
       
        List<OrderItem> oi = TestDataFactory.createOrderItemWithLeave(1,'SL');
		Test.startTest();
     	
       
       	boolean result = InvoiceBuilder.GenerateInvoices(job.Id);
    
        Test.stopTest();
        
        system.assert(result == true);
    }
        
}