src/objects/Batch_Jobs__c.object
<CustomObject>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>false</active>
        <description>A batch that has not been submitted</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Leave_Taken_This_Year__c</fullName>
        <formula>Leave_Taken_Sunday__c +  Leave_Taken_Monday__c  +  Leave_Taken_Tuesday__c +  Leave_Taken_Wednesday__c +  Leave_Taken_Thursday__c  + Leave_Taken_Friday__c + Leave_Taken_Saturday__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Leave Taken This Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New stall selector, this should be hidden and used for ui of adding a new stall to the opp</description>
        <label>Stall</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Stall__c.RecordType.DeveloperName</field>
                <operation>notContain</operation>
                <value>Perm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>LH</fullName>
        <active>true</active>
        <businessProcess>QVM Account Business Sales Process</businessProcess>
        <description>Lease Hold Record Type for QVM Account Businesses</description>
        <label>LH</label>
    </recordTypes>
    <recordTypes>
        <fullName>SL</fullName>
        <active>true</active>
        <businessProcess>QVM Account Business Sales Process</businessProcess>
        <description>Stall Hold Licenses record Type for QVM Account Businesses</description>
        <label>SL</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderBuilderTest.cls
@isTest
private class OrderBuilderTest {

    private class Mock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            
            system.debug('hi there');
            HTTPResponse res = new HTTPResponse();
            res.setStatusCode(200);
           
            
            String json = '{'+
                '  \"Customer\": {'+
                '    \"Taxable\": false,'+
                '    \"Job\": false,'+
                '    \"BillWithParent\": false,'+
                '    \"Balance\": 0,'+
                '    \"BalanceWithJobs\": 0,'+
                '    \"CurrencyRef\": {'+
                '      \"value\": \"AUD\",'+
                '      \"name\": \"Australian Dollar\"'+
                '    },'+
                '    \"PreferredDeliveryMethod\": \"None\",'+
                '    \"PrimaryTaxIdentifier\": \"XXXX2352345\",'+
                '    \"domain\": \"QBO\",'+
                '    \"sparse\": false,'+
                '    \"Id\": \"89\",'+
                '    \"SyncToken\": \"0\",'+
                '    \"MetaData\": {'+
                '      \"CreateTime\": \"2016-08-23T20:57:44-07:00\",'+
                '      \"LastUpdatedTime\": \"2016-08-23T20:57:44-07:00\"'+
                '    },'+
                '    \"FullyQualifiedName\": \"www1\",'+
                '    \"CompanyName\": \"www1\",'+
                '    \"DisplayName\": \"www1\",'+
                '    \"PrintOnCheckName\": \"www1\",'+
                '    \"Active\": true'+
                '  },'+
                '  \"time\": \"2016-08-23T20:57:44.496-07:00\"'+
                '}';
             res.setBody(json);
           
            return res;
        }
    }
    
    @isTest static void TestGenerateOrdersSL() {
        List<Account> accounts = TestDataFactory.createAccountsWithOpps(1,1, 'SL');

        TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new Mock());
        TestDataFactory.createStallProductsAndGeneralPriceBook();

        Opportunity opp = [select id, name, Stall__c from Opportunity limit 1];
        TestDataFactory.createSingleStall(opp);

        Batch_Jobs__c job = TestDataFactory.createSLBatchJob();
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Batch_Jobs__c; 
        Map<String,Schema.RecordTypeInfo> BatchJobsTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = BatchJobsTypeInfo.get('New Orders/Invoices').getRecordTypeId();
            
        system.debug('TEST : ' + rtId);

        Test.startTest();
     
        boolean result = OrderBuilder.GenerateOrders(job.Id );
    
        Test.stopTest();
        
            

        //System.assert(opp3.Leave_Taken_This_Year__c == 0);

    }

    
    @isTest static void TestGenerateOrdersLH() {
        List<Account> accounts = TestDataFactory.createAccountsWithOpps(1,1, 'LH');

        TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new Mock());
        
        TestDataFactory.createStallProductsAndGeneralPriceBook();

        Opportunity opp = [select id, name, Stall__c  from Opportunity limit 1];
        TestDataFactory.createPermStallWithOpp(opp);

        Batch_Jobs__c job = TestDataFactory.createLHBatchJob();

        Test.startTest();
     
        boolean result = OrderBuilder.GenerateOrders(job.Id );
    
        Test.stopTest();
    
        //System.assert(opp3.Leave_Taken_This_Year__c == 0);

    }
    
    @isTest static void TestGenerateOrdersFees() {
        List<Account> accounts = TestDataFactory.createAccountsWithOpps(1,1, 'LH');

        TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new Mock());
        
        TestDataFactory.createStallProductsAndGeneralPriceBook();

        Opportunity opp = [select id, name, Stall__c  from Opportunity limit 1];
        TestDataFactory.createPermStallWithOpp(opp);

        Batch_Jobs__c job = TestDataFactory.createMCCBatchJob();
        TestDataFactory.CreateQVM_LH_FEE_SETTING_Entries();

        Test.startTest();
     
        boolean result = OrderBuilder.GenerateOrders(job.Id );
    
        Test.stopTest();
    
        //System.assert(opp3.Leave_Taken_This_Year__c == 0);

    }
    
}