src/objects/Batch_Jobs__c.object
<CustomObject>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>false</active>
        <description>A batch that has not been submitted</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Leave__c.object
<CustomObject>
    <description>The leave requests for a trader</description>
    <fields>
        <fullName>Account_Business__c</fullName>
        <description>The account business (Opp) that the leave is allocated against</description>
        <inlineHelpText>The account business that the leave is allocated against</inlineHelpText>
        <label>Account Business</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Leave</relationshipLabel>
        <relationshipName>Leave</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Leave_Date__c</fullName>
        <description>The date the leave is for</description>
        <inlineHelpText>The date the leave is for</inlineHelpText>
        <label>Leave Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Leave</label>
    <nameField>
        <displayFormat>L-{000000000}</displayFormat>
        <label>Leave Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Leave_Taken_This_Year__c</fullName>
        <formula>Leave_Taken_Sunday__c +  Leave_Taken_Monday__c  +  Leave_Taken_Tuesday__c +  Leave_Taken_Wednesday__c +  Leave_Taken_Thursday__c  + Leave_Taken_Friday__c + Leave_Taken_Saturday__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Leave Taken This Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New stall selector, this should be hidden and used for ui of adding a new stall to the opp</description>
        <label>Stall</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Stall__c.RecordType.DeveloperName</field>
                <operation>notContain</operation>
                <value>Perm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>SL</fullName>
        <active>true</active>
        <businessProcess>QVM Account Business Sales Process</businessProcess>
        <description>Stall Hold Licenses record Type for QVM Account Businesses</description>
        <label>SL</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <fields>
        <fullName>FridayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Friday</description>
        <inlineHelpText>The Account Business allocated to this stall on Friday</inlineHelpText>
        <label>Friday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Friday Stalls</relationshipLabel>
        <relationshipName>FridayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MondayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Mondays</description>
        <inlineHelpText>The Account Business allocated to this stall on Mondays</inlineHelpText>
        <label>Monday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Monday Stalls</relationshipLabel>
        <relationshipName>MondayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SaturdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Saturday</description>
        <inlineHelpText>The Account Business allocated to this stall on Saturday</inlineHelpText>
        <label>Saturday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Saturday Stalls</relationshipLabel>
        <relationshipName>SaturdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SundayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Sunday</description>
        <inlineHelpText>The Account Business allocated to this stall on Sunday</inlineHelpText>
        <label>Sunday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sunday Stalls</relationshipLabel>
        <relationshipName>SundayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ThursdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Thursday</description>
        <inlineHelpText>The Account Business allocated to this stall on Thursday</inlineHelpText>
        <label>Thursday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Thursday Stalls</relationshipLabel>
        <relationshipName>ThursdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TuesdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Tuesday</description>
        <inlineHelpText>The Account Business allocated to this stall on Tuesday</inlineHelpText>
        <label>Tuesday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tuesday Stalls</relationshipLabel>
        <relationshipName>TuesdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WednesdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Wednesday</description>
        <inlineHelpText>The Account Business allocated to this stall on Wednesday</inlineHelpText>
        <label>Wednesday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Wednesday Stalls</relationshipLabel>
        <relationshipName>WednesdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeaveTriggerTest.cls
@isTest
private class LeaveTriggerTest {
    
    
  private class Mock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            
            system.debug('hi there');
            HTTPResponse res = new HTTPResponse();
            res.setStatusCode(200);
           
            
            String json = '{'+
                '  \"Customer\": {'+
                '    \"Taxable\": false,'+
                '    \"Job\": false,'+
                '    \"BillWithParent\": false,'+
                '    \"Balance\": 0,'+
                '    \"BalanceWithJobs\": 0,'+
                '    \"CurrencyRef\": {'+
                '      \"value\": \"AUD\",'+
                '      \"name\": \"Australian Dollar\"'+
                '    },'+
                '    \"PreferredDeliveryMethod\": \"None\",'+
                '    \"PrimaryTaxIdentifier\": \"XXXX2352345\",'+
                '    \"domain\": \"QBO\",'+
                '    \"sparse\": false,'+
                '    \"Id\": \"89\",'+
                '    \"SyncToken\": \"0\",'+
                '    \"MetaData\": {'+
                '      \"CreateTime\": \"2016-08-23T20:57:44-07:00\",'+
                '      \"LastUpdatedTime\": \"2016-08-23T20:57:44-07:00\"'+
                '    },'+
                '    \"FullyQualifiedName\": \"www1\",'+
                '    \"CompanyName\": \"www1\",'+
                '    \"DisplayName\": \"www1\",'+
                '    \"PrintOnCheckName\": \"www1\",'+
                '    \"Active\": true'+
                '  },'+
                '  \"time\": \"2016-08-23T20:57:44.496-07:00\"'+
                '}';
           	res.setBody(json);
           
            return res;
        }
    }
    
    
    @isTest static void TestLeaveTrigger() {
    
        TestDataFactory.CreateOAuthServiceEntries();
        
        Test.setMock(HttpCalloutMock.class, new Mock());
        Test.startTest();
        List<Account> accounts = TestDataFactory.createAccountsWithOpps(1,1, 'SL');


        TestDataFactory.createStallProductsAndGeneralPriceBook();

        Opportunity opp = [select id, name, Stall__c from Opportunity limit 1];
        TestDataFactory.createSingleStall(opp);

        Batch_Jobs__c job = TestDataFactory.createSLBatchJob();

        //where id = '006p0000002kWG0AAM'
        

        List<Opportunity> opps = [select Id, Name, accountid, pricebook2id
                          ,(select id from MondayStalls__r)
                          ,(select id from TuesdayStalls__r)
                          ,(select id from WednesdayStalls__r)
                          ,(select id from ThursdayStalls__r)
                          ,(select id from FridayStalls__r)
                          ,(select id from SaturdayStalls__r)
                          ,(select id from SundayStalls__r)
                          from opportunity
                          ];



        //boolean result = OrderBuilder.GenerateOrders(job.Id );
        boolean result = OrderBuilder.GenerateOrdersFromAllocatedStalls( Date.today(),Date.today() + 6, opps, job.Id, '' );
       
        Test.stopTest();
        
            

        
        opp = [select id, name, Stall__c from Opportunity limit 1];
        // test adding each day of the week 
        List<Leave__c> leaveToAdd = new List<Leave__c>();
        Integer i = 1;
        while (i < 8)
        {
            Leave__c leave = new Leave__c();
            leave.Account_Business__c = opp.Id;
            leave.Leave_Date__c = Date.today().addDays(i);
            leaveToAdd.add(leave);
            i++;
        }
        

        Insert leaveToAdd;

        Opportunity opp2 = [select id, name, Leave_Taken_This_Year__c from Opportunity limit 1];    

        System.assert(opp2.Leave_Taken_This_Year__c == 7);

        Delete leaveToAdd;

        Opportunity opp3 = [select id, name, Leave_Taken_This_Year__c from Opportunity limit 1];    

        System.assert(opp3.Leave_Taken_This_Year__c == 0);

    }
    

    
}