src/objects/Batch_Jobs__c.object
<CustomObject>
    <label>Batch Jobs</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>false</active>
        <description>A batch that has not been submitted</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New stall selector, this should be hidden and used for ui of adding a new stall to the opp</description>
        <label>Stall</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Stall__c.RecordType.DeveloperName</field>
                <operation>notContain</operation>
                <value>Perm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>SL</fullName>
        <active>true</active>
        <businessProcess>QVM Account Business Sales Process</businessProcess>
        <description>Stall Hold Licenses record Type for QVM Account Businesses</description>
        <label>SL</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Batch_Jobs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The batch job that processd the credit note for the flagged leave</description>
        <label>Batch Jobs</label>
        <referenceTo>Batch_Jobs__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Leave_Cretits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stall</label>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeaveCreditNoteBuilderTest.cls
@isTest
public class LeaveCreditNoteBuilderTest {
    /*
    private class Mock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            
            system.debug('hi there');
            HTTPResponse res = new HTTPResponse();
            res.setStatusCode(200);
            
            String json = '';
            if (req.getEndpoint().contains('customer')){
                json = '{'+
                    '  \"Customer\": {'+
                    '    \"Taxable\": false,'+
                    '    \"Job\": false,'+
                    '    \"BillWithParent\": false,'+
                    '    \"Balance\": 0,'+
                    '    \"BalanceWithJobs\": 0,'+
                    '    \"CurrencyRef\": {'+
                    '      \"value\": \"AUD\",'+
                    '      \"name\": \"Australian Dollar\"'+
                    '    },'+
                    '    \"PreferredDeliveryMethod\": \"None\",'+
                    '    \"PrimaryTaxIdentifier\": \"XXXX2352345\",'+
                    '    \"domain\": \"QBO\",'+
                    '    \"sparse\": false,'+
                    '    \"Id\": \"89\",'+
                    '    \"SyncToken\": \"0\",'+
                    '    \"MetaData\": {'+
                    '      \"CreateTime\": \"2016-08-23T20:57:44-07:00\",'+
                    '      \"LastUpdatedTime\": \"2016-08-23T20:57:44-07:00\"'+
                    '    },'+
                    '    \"FullyQualifiedName\": \"www1\",'+
                    '    \"CompanyName\": \"www1\",'+
                    '    \"DisplayName\": \"www1\",'+
                    '    \"PrintOnCheckName\": \"www1\",'+
                    '    \"Active\": true'+
                    '  },'+
                    '  \"time\": \"2016-08-23T20:57:44.496-07:00\"'+
                    '}';
            }
            else if(req.getEndpoint().contains('query'))
            {
                json = '{'+
                    '  \"QueryResponse\": {'+
                    '    \"Item\": ['+
                    '      {'+
                    '        \"SalesTaxCodeRef\": {'+
                    '          \"value\": \"10\",'+
                    '          \"name\": \"SalesTaxCodeRef\"'+
                    '        },'+
                    '        \"sparse\": true,'+
                    '        \"Id\": \"20\"'+
                    '      },'+
                    '      {'+
                    '        \"SalesTaxCodeRef\": {'+
                    '          \"value\": \"10\",'+
                    '          \"name\": \"SalesTaxCodeRef\"'+
                    '        },'+
                    '        \"sparse\": true,'+
                    '        \"Id\": \"1\"'+
                    '      }'+
                    '    ],'+
                    '    \"startPosition\": 1,'+
                    '    \"maxResults\": 2'+
                    '  }' + 
                    '}';
                
            }
            
            res.setBody(json);
            
            return res;
        }
    }*/
    
    @isTest static void TestGenerateLeaveCreditNotes(){
        TestDataFactory.createStallProductsAndGeneralPriceBook();
        TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());
        List<Account> accounts = TestDataFactory.createAccountsWithOpps(1,1, 'SL');
        
        Opportunity opp = [select id, name, Stall__c from Opportunity limit 1];
        TestDataFactory.createSingleStall(opp);
        
        Batch_Jobs__c job = TestDataFactory.createSLBatchJobLCN();
        Test.startTest();
        boolean result = LeaveCreditNoteBuilder.GenerateLeaveCreditNotes(job.Id);
        System.assert(result);
        Test.stopTest();
    }
    
    @isTest static void TestGenerateLeaveCreditNotesWithLeave(){
        
        TestDataFactory.createStallProductsAndGeneralPriceBook();
        TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());
        List<Account> accounts = TestDataFactory.createAccountsWithOpps(1,1, 'SL');
        
        Opportunity opp = [select id, name, Stall__c from Opportunity limit 1];
        TestDataFactory.createSingleStall(opp);
        
        Batch_Jobs__c job = TestDataFactory.createSLBatchJobLCN();
        List<OrderItem> oi = TestDataFactory.createOrderItemWithLeave(1,'SL');
        Test.startTest();
        Map<string, QBOProductList.Item >  productMap = new Map<string, QBOProductList.Item  >();
        boolean resultSuccess = LeaveCreditNoteBuilder.GenerateLeaveCreditNotes(null);
        System.assert(resultSuccess);
        Test.stopTest();
        
        
    }
   
    
}