src/objects/Leave__c.object
<CustomObject>
    <description>The leave requests for a trader</description>
    <fields>
        <fullName>Account_Business__c</fullName>
        <description>The account business (Opp) that the leave is allocated against</description>
        <inlineHelpText>The account business that the leave is allocated against</inlineHelpText>
        <label>Account Business</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Leave</relationshipLabel>
        <relationshipName>Leave</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Leave_Date__c</fullName>
        <description>The date the leave is for</description>
        <inlineHelpText>The date the leave is for</inlineHelpText>
        <label>Leave Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Leave</label>
    <nameField>
        <displayFormat>L-{000000000}</displayFormat>
        <label>Leave Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Leave_Remaining_Friday__c</fullName>
        <formula>Contracted_Leave__c -  Leave_Taken_Friday__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Leave Remaining Friday</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Leave_Remaining_Monday__c</fullName>
        <formula>Contracted_Leave__c -  Leave_Taken_Monday__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Leave Remaining Monday</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Leave_Remaining_Saturday__c</fullName>
        <formula>Contracted_Leave__c -  Leave_Taken_Saturday__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Leave Remaining Saturday</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Leave_Remaining_Sunday__c</fullName>
        <formula>Contracted_Leave__c -  Leave_Taken_Sunday__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Leave Remaining Sunday</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Leave_Remaining_Thursday__c</fullName>
        <formula>Contracted_Leave__c -  Leave_Taken_Thursday__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Leave Remaining Thursday</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Leave_Remaining_Tuesday__c</fullName>
        <formula>Contracted_Leave__c -  Leave_Taken_Tuesday__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Leave Remaining Tuesday</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Leave_Remaining_Wednesday__c</fullName>
        <formula>Contracted_Leave__c -  Leave_Taken_Wednesday__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Leave Remaining Wednesday</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LeaveController.cls
public without sharing class LeaveController {
    @AuraEnabled
    public static String getAccountId(){
        String accId = [SELECT AccountId FROM User WHERE Id = :userinfo.getUserId()].AccountId;
        return accId;
    }
    @AuraEnabled
    public static List<Opportunity> getAccountBusiness() {
        
        String accId = LeaveController.getAccountId();
        if(accId != null){
            List<Opportunity> accBusiness = [SELECT Id,Name,RecordType.Name,Leave_Remaining_Monday__c,Leave_Remaining_Tuesday__c,Leave_Remaining_Wednesday__c,
                                             Leave_Remaining_Thursday__c,Leave_Remaining_Friday__c,Leave_Remaining_Saturday__c,Leave_Remaining_Sunday__c
                                             , (select id, Name,Leave_Date__c from Leave__r)
                                             FROM Opportunity
                                             WHERE AccountId  = :accId];
            System.debug('PP '+accBusiness.get(0).RecordType.Name);
            System.debug('accBusiness '+accBusiness);
            if(accBusiness != null){
                return accBusiness;
            }
            else
                return null;
        }
        else
            return null;
    }
    
    @AuraEnabled
    public static void createLeave(String accBusinessId, String leaveDate) {
        System.debug('Hello accBusinessId '+accBusinessId);
        System.debug('Hello leaveDate '+leaveDate);
        if(accBusinessId != null && leaveDate != null){
            Leave__c leaveObj = new Leave__c();
            leaveObj.Account_Business__c = accBusinessId;
            leaveObj.Leave_Date__c = Date.valueOf(leaveDate);
            insert leaveObj;
            
        }
    }
    
}