src/objects/Leave__c.object
<CustomObject>
    <description>The leave requests for a trader</description>
    <label>Leave</label>
    <nameField>
        <displayFormat>L-{000000000}</displayFormat>
        <label>Leave Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The date the order items was for</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Leave__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flags if the trader is on leave for this order item. If this is true then the space will be available for casual traders.</description>
        <label>On Leave</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stall</label>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Select if this stall is still a valid stall</inlineHelpText>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShedId__c</fullName>
        <label>Shed Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <recordTypes>
        <fullName>Casual</fullName>
        <active>true</active>
        <description>Stall locations that can change trader on a day to day basis</description>
        <label>Casual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StallsAvaliableTodayController.cls
public with sharing class StallsAvaliableTodayController {

	 public String laneID{get;set;}
    
	 public List<Stall__c> getStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                order by Name 
                LIMIT 1000];

    }
    /*
    public List<Stall__c> getSelectStallsAvaliableToday() {
        
        laneID = Apexpages.currentPage().getParameters().get('laneID');
        System.debug(laneID);
		

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and ShedId__c = :laneID
                order by Name 
                LIMIT 1000];

    }
*/
    
    public List<Stall__c> getAStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and ShedId__c = 'A'
                order by Name 
                LIMIT 1000];

    }
    
    public List<Stall__c> getBStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and ShedId__c = 'B'
                order by Name 
                LIMIT 1000];

    }
    
    public List<Stall__c> getCStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and ShedId__c = 'C'
                order by Name 
                LIMIT 1000];

    }
    
    public List<Stall__c> getDStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and ShedId__c = 'D'
                order by Name 
                LIMIT 1000];

    }
    
    public List<Stall__c> getEStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and ShedId__c = 'E'
                order by Name 
                LIMIT 1000];

    }
    
    public List<Stall__c> getHStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and ShedId__c = 'H'
                order by Name 
                LIMIT 1000];

    }
    
    public List<Stall__c> getIStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and ShedId__c = 'I'
                order by Name 
                LIMIT 1000];

    }
    
    public List<Stall__c> getJStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and ShedId__c = 'J'
                order by Name 
                LIMIT 1000];

    }
    
    public List<Stall__c> getKStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and ShedId__c = 'K'
                order by Name 
                LIMIT 1000];

    }
    
    public List<Stall__c> getLStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and ShedId__c = 'L'
                order by Name 
                LIMIT 1000];

    }
    
    public List<Stall__c> getRKStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and ShedId__c = 'RK'
                order by Name 
                LIMIT 1000];

    }
    
    public List<Stall__c> getRLStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and ShedId__c = 'RL'
                order by Name 
                LIMIT 1000];

    }
    
    public List<Stall__c> getOtherStallsAvaliableToday() {

        return [SELECT Name, IsActive__c, ShedId__c FROM Stall__c WHERE Id NOT IN 
                	(SELECT Stall__c 
                    FROM OrderItem
                    WHERE Date__c = TODAY AND Leave__c = FALSE
                    AND Stall__c  != NULL)  
                and RecordType.Name = 'Casual'
                and IsActive__c = true
                and (ShedId__c <> 'A' AND ShedId__c <> 'B' AND ShedId__c <> 'C' AND ShedId__c <> 'D' AND ShedId__c <> 'E' AND ShedId__c <> 'J' AND ShedId__c <> 'K' AND ShedId__c <> 'L' AND ShedId__c <> 'RK' AND ShedId__c <> 'RL' AND ShedId__c <> 'H' AND ShedId__c <> 'I')
                order by Name 
                LIMIT 1000];

    }
    


}