src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New stall selector, this should be hidden and used for ui of adding a new stall to the opp</description>
        <label>Stall</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Stall__c.RecordType.DeveloperName</field>
                <operation>notContain</operation>
                <value>Perm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <fields>
        <fullName>FridayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Friday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Friday</inlineHelpText>
        <label>Friday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FridayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Friday</description>
        <inlineHelpText>The Account Business allocated to this stall on Friday</inlineHelpText>
        <label>Friday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Friday Stalls</relationshipLabel>
        <relationshipName>FridayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Friday_Active_Price__c</fullName>
        <label>Friday Active Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MondayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Monday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Monday</inlineHelpText>
        <label>Monday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MondayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Mondays</description>
        <inlineHelpText>The Account Business allocated to this stall on Mondays</inlineHelpText>
        <label>Monday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Monday Stalls</relationshipLabel>
        <relationshipName>MondayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monday_Active_Price__c</fullName>
        <label>Monday Active Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SaturdayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Saturday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Saturday</inlineHelpText>
        <label>Saturday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SaturdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Saturday</description>
        <inlineHelpText>The Account Business allocated to this stall on Saturday</inlineHelpText>
        <label>Saturday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Saturday Stalls</relationshipLabel>
        <relationshipName>SaturdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Saturday_Active_Price__c</fullName>
        <label>Saturday Active Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SundayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Sunday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Sunday</inlineHelpText>
        <label>Sunday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SundayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Sunday</description>
        <inlineHelpText>The Account Business allocated to this stall on Sunday</inlineHelpText>
        <label>Sunday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sunday Stalls</relationshipLabel>
        <relationshipName>SundayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sunday_Active_Price__c</fullName>
        <label>Sunday Active Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ThursdayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Thursday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Thursday</inlineHelpText>
        <label>Thursday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ThursdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Thursday</description>
        <inlineHelpText>The Account Business allocated to this stall on Thursday</inlineHelpText>
        <label>Thursday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Thursday Stalls</relationshipLabel>
        <relationshipName>ThursdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Thursday_Active_Price__c</fullName>
        <label>Thursday Active Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TuesdayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Tuesday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Tuesday</inlineHelpText>
        <label>Tuesday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TuesdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Tuesday</description>
        <inlineHelpText>The Account Business allocated to this stall on Tuesday</inlineHelpText>
        <label>Tuesday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tuesday Stalls</relationshipLabel>
        <relationshipName>TuesdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tuesday_Active_Price__c</fullName>
        <label>Tuesday Active Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WednesdayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Wednesday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Wednesday</inlineHelpText>
        <label>Wednesday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WednesdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Wednesday</description>
        <inlineHelpText>The Account Business allocated to this stall on Wednesday</inlineHelpText>
        <label>Wednesday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Wednesday Stalls</relationshipLabel>
        <relationshipName>WednesdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wednesday_Active_Price__c</fullName>
        <label>Wednesday Active Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerHelper.cls
public class OpportunityTriggerHelper {
	public static void UpdateStallValues(List<Opportunity> opps)
    {
        set<Id> oppIds = new set<Id>();
        
        for (Opportunity opp : opps)
        {
            oppIds.add(opp.Id);
        }
        
        
        list<Stall__c> stalls = [SELECT FridayTrader__c,MondayTrader__c,Name,SaturdayTrader__c
                                        ,SundayTrader__c,ThursdayTrader__c,TuesdayTrader__c,WednesdayTrader__c
               					,Friday_Active_Price__c,Monday_Active_Price__c,Saturday_Active_Price__c
               					,Sunday_Active_Price__c,Thursday_Active_Price__c,Tuesday_Active_Price__c
               					,Wednesday_Active_Price__c, FridayMultiplier__c,MondayMultiplier__c
                                ,SaturdayMultiplier__c,SundayMultiplier__c,ThursdayMultiplier__c
                                 ,TuesdayMultiplier__c,WednesdayMultiplier__c
               					FROM Stall__c
                                where MondayTrader__c in  :oppIds    or
                                TuesdayTrader__c in  :oppIds    or
                                WednesdayTrader__c in  :oppIds   or
                                ThursdayTrader__c in  :oppIds   or
                                FridayTrader__c in  :oppIds or
                                SaturdayTrader__c in  :oppIds  or
                                SundayTrader__c in  :oppIds ];
        
        update StallTriggerHelper.UpdateStallValues(stalls);
        
    }
}