src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New stall selector, this should be hidden and used for ui of adding a new stall to the opp</description>
        <label>Stall</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Stall__c.RecordType.DeveloperName</field>
                <operation>notContain</operation>
                <value>Perm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Uplift_Factor__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The amount multiplied against the a SL traders rates</description>
        <inlineHelpText>The amount multiplied against the a SL traders rates</inlineHelpText>
        <label>Uplift Factor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>SLPE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CHECK IF USED MY SL or PE</description>
        <inlineHelpText>CHECK IF USED MY SL or PE</inlineHelpText>
        <label>SLPE</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <fields>
        <fullName>FridayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Friday</description>
        <inlineHelpText>The Account Business allocated to this stall on Friday</inlineHelpText>
        <label>Friday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Friday Stalls</relationshipLabel>
        <relationshipName>FridayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MondayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Mondays</description>
        <inlineHelpText>The Account Business allocated to this stall on Mondays</inlineHelpText>
        <label>Monday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Monday Stalls</relationshipLabel>
        <relationshipName>MondayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SaturdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Saturday</description>
        <inlineHelpText>The Account Business allocated to this stall on Saturday</inlineHelpText>
        <label>Saturday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Saturday Stalls</relationshipLabel>
        <relationshipName>SaturdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SundayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Sunday</description>
        <inlineHelpText>The Account Business allocated to this stall on Sunday</inlineHelpText>
        <label>Sunday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sunday Stalls</relationshipLabel>
        <relationshipName>SundayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ThursdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Thursday</description>
        <inlineHelpText>The Account Business allocated to this stall on Thursday</inlineHelpText>
        <label>Thursday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Thursday Stalls</relationshipLabel>
        <relationshipName>ThursdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TuesdayMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Multiplier rate that will be added to the base rate for Tuesday</description>
        <inlineHelpText>The Multiplier rate that will be added to the base rate for Tuesday</inlineHelpText>
        <label>Tuesday Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TuesdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Tuesday</description>
        <inlineHelpText>The Account Business allocated to this stall on Tuesday</inlineHelpText>
        <label>Tuesday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tuesday Stalls</relationshipLabel>
        <relationshipName>TuesdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tuesday_Active_Price__c</fullName>
        <label>Tuesday Active Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WednesdayTrader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity (Account Business) allocated to this stall on Wednesday</description>
        <inlineHelpText>The Account Business allocated to this stall on Wednesday</inlineHelpText>
        <label>Wednesday Trader</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Wednesday Stalls</relationshipLabel>
        <relationshipName>WednesdayStalls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StallTriggerHelper.cls
public class StallTriggerHelper {

    public static void UpdateStallValues(List<Stall__c> stalls)
    {
        //GET ALL THE PRICES
        list<PricebookEntry> prices = [SELECT ProductCode,UnitPrice,  Pricebook2.Name,  Pricebook2Id FROM PricebookEntry where Pricebook2.SLPE__c = true ];
        map<String,PricebookEntry> pricesMap = new map<String,PricebookEntry>();
        for (PricebookEntry price : prices)
        {
            pricesMap.put(price.ProductCode + price.Pricebook2Id , price);
        }
        
        // GET ALL THE TRADER INVOLVED
        SET<Id> traderIds = new SET<Id>();
        for (Stall__c stall : stalls )
        {
           traderIds.add(stall.MondayTrader__c);
           traderIds.add(stall.TuesdayTrader__c);
           traderIds.add(stall.WednesdayTrader__c);
           traderIds.add(stall.ThursdayTrader__c);
           traderIds.add(stall.FridayTrader__c);
           traderIds.add(stall.SaturdayTrader__c);
           traderIds.add(stall.SundayTrader__c);
        }
        List<Opportunity> traders = [SELECT Id, Pricebook2Id,Uplift_Factor__c from Opportunity where Id in :traderIds];
        // asdd traders to map
        Map<Id , Opportunity> traderMap = new Map<Id , Opportunity>();
        for (Opportunity trader : traders)
        {
            traderMap.put(trader.Id, trader);
        }
        
        
        for (Stall__c stall : stalls )
        {
            String priceKey = '' ;
            if(stall.TuesdayTrader__c != null)
            {
                system.debug('traderMap.get(stall.TuesdayTrader__c).Pricebook2Id:' + traderMap.get(stall.TuesdayTrader__c).Pricebook2Id);
                priceKey = 'Tuesday' + traderMap.get(stall.TuesdayTrader__c).Pricebook2Id;
                double price = pricesMap.get(priceKey).UnitPrice;
                system.debug('price' + price );
                system.debug('price' + price );
                system.debug('price' + price );
                stall.Tuesday_Active_Price__c = price * traderMap.get(stall.TuesdayTrader__c).Uplift_Factor__c *  stall.TuesdayMultiplier__c;
            }
            
        }
        
    }
}