src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Total__c</fullName>
        <description>The office total to be used . Replaces order amount as it factors in the opp uplift factor and the the stall multipliers</description>
        <inlineHelpText>The grand total for the order</inlineHelpText>
        <label>Total</label>
        <summarizedField>OrderItem.Total__c</summarizedField>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The date the order items was for</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Formula_Total__c</fullName>
        <formula>UnitPrice  * 
Quantity * 
CASE( PricebookEntry.Product2.ProductCode , 
   &apos;Monday&apos;, BLANKVALUE(Stall__r.MondayMultiplier__c,1), 
   &apos;Tuesday&apos;, BLANKVALUE(Stall__r.TuesdayMultiplier__c,1) , 
   &apos;Wednesday&apos;, BLANKVALUE(Stall__r.WednesdayMultiplier__c,1) , 
   &apos;Thursday&apos;, BLANKVALUE(Stall__r.ThursdayMultiplier__c,1), 
   &apos;Friday&apos;, BLANKVALUE(Stall__r.FridayMultiplier__c,1), 
   &apos;Saturday&apos;, BLANKVALUE(Stall__r.SaturdayMultiplier__c,1), 
   &apos;Sunday&apos;, BLANKVALUE(Stall__r.SundayMultiplier__c,1),1) *   BLANKVALUE(Order.Opportunity.Uplift_Factor__c, 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formula Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stall__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stall</label>
        <referenceTo>Stall__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <defaultValue>0</defaultValue>
        <description>To be used instead of  Total Price for the total line price</description>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PrintToPDFController.cls
public class PrintToPDFController {

    public String orderId {get;set;}
    public List<OrderItem> orderItems {get;set;}
    public PrintToPDFController(ApexPages.StandardController controller){
        orderId = ApexPages.currentPage().getParameters().get('Id');
        orderItems = [SELECT PricebookEntry.Product2.Name,Stall__r.Name,Date__c,Description,Quantity,
                                      UnitPrice,Formula_Total__c, Total__c
                                      FROM OrderItem 
        							  WHERE Order.Id = :orderId];
        
        /*for(OrderItem oi : orderItems){
            
        }*/
    }
    /*TotalPrice
    public String orderId {get;set;}
    public PrintToPDFController() {
        orderId = ApexPages.currentPage().getParameters().get('Id');
    }
    
    public String PrintableView {
        get{
        Id myid = ApexPages.currentPage().getParameters().get('Id');
        String html = new PageReference('/' + myid + '/p').getContent().toString();
        System.debug('Yay '+html.substringAfter('</head>').substringBefore('</html>'));
        return html.substringAfter('</head>').substringBefore('</html>');
        }
    }
	*/

}