src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>PO_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the order has been approved as a PO</description>
        <label>PO Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuickBooksId__c</fullName>
        <externalId>true</externalId>
        <label>QuickBooksId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderTriggerTest.cls
@isTest public class OrderTriggerTest {
    @isTest 
    static void TestGeneratePuchaseOrder() {
        TestDataFactory.CreateOAuthServiceEntries();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockEngine());
        TestDataFactory.createStallProductsAndGeneralPriceBook();
        Order order = TestDataFactory.createPO();
        system.debug('Test:: ' + order.QuickBooksId__c);
        order.PO_Approved__c = true;
        update order;
    }
}