src/objects/qvm_intuit_api__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>OAuth and endpoint settings for connecting to the Intuit REST API for Quickbooks</description>
    <fields>
        <fullName>ApiName__c</fullName>
        <defaultValue>&quot;Intuit&quot;</defaultValue>
        <label>API Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ConsumerKey__c</fullName>
        <label>Consumer key</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerSecret__c</fullName>
        <label>ConsumerSecret</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Realm__c</fullName>
        <label>Quickbooks Company ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceBaseAddress__c</fullName>
        <defaultValue>&quot;https://sandbox-quickbooks.api.intuit.com/v3/&quot;</defaultValue>
        <label>Service base address</label>
        <type>Url</type>
    </fields>
    <label>QVM Intuit QuickBooks API</label>
</CustomObject>

src/objects/qvm_intuit_api_token__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Realm__c</fullName>
        <label>Realm</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TokenSecret__c</fullName>
        <description>The token&apos;s secret key.  This will be blank while the OAuth connect process is under way</description>
        <label>Token secret</label>
        <length>130</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>130</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Quickbooks API Token</label>
</CustomObject>

src/classes/IntuitServiceTests.cls
@isTest
class IntuitServiceTests {
    private static final String TEST_API_NAME='Intuit_test';

    @testSetup 
    static void setupTest()
    {
        setupSettings();
        setupToken();
    }
    static void setupSettings(){
        qvm_intuit_api__c settings = new qvm_intuit_api__c();
        settings.ApiName__c = TEST_API_NAME;
        settings.ServiceBaseAddress__c = 'https://sandbox-quickbooks.api.intuit.com/v3/company/{realm}/';
        settings.ConsumerKey__c ='qyprdBeCEyz8XgXyQLhGyVKFJxSj5R';
        settings.ConsumerSecret__c='d89SNefvcrnlgY1ot88GL1uhviL68L5MenIhjZmw';
        insert settings; 
    }
    static void setupToken(){
        qvm_intuit_api_token__c settings = new qvm_intuit_api_token__c();
        settings.Name = TEST_API_NAME;
        settings.Token__c ='qyprdIx7WetkvVG49F5VGZU09h8AfGMczXhjW8LyTzdSiw4t';
        settings.TokenSecret__c='k21QG4eRHBo1rQf1RgZmtsYFRreBMRUyldFtTNeN';
        settings.Realm__c='193514335420637';
        insert settings;
    }
   
    @isTest
    static void sample()
    {
        HttpClient client = IntuitService.createClient();
        MockHttpRequestDispatcher dispatcher = new MockHttpRequestDispatcher();

        client.messageHandler.setDispatcher(dispatcher);
        dispatcher.handleRequest().jsonContent('{"Name":"Value"}');
        String response= (String) client.jsonGet('query?query=select * from Customer', String.class);
        Assert.areEqual('{"Name":"Value"}', response);

    }
    @isTest
    static void readConfig(){
        IntuitService.Configuration config= IntuitService.getConfig();
        Assert.areEqual('Intuit_test',config.getApiName());
        Assert.areEqual('https://sandbox-quickbooks.api.intuit.com/v3/company/193514335420637/',config.getServiceBaseAddress());
    }
}