src/objects/Stall__c.object
<CustomObject>
    <description>A space in the market that is flexible. These spaces are in the sheds or out side.</description>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Left__c</fullName>
        <label>Left</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Line_Height__c</fullName>
        <label>Line Height</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Top__c</fullName>
        <label>Top</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Stall</label>
    <nameField>
        <label>Stall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stalls</pluralLabel>
    <recordTypes>
        <fullName>Casual</fullName>
        <active>true</active>
        <description>Stall locations that can change trader on a day to day basis</description>
        <label>Casual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StallMapController.cls
public class StallMapController {

    
    public String getbuildTable(){
        
        String tmp;
        
        List<Stall__c> stalls = [SELECT Name,Height__c,Left__c,Line_Height__c,Top__c,Width__c FROM Stall__c 
                                 WHERE RecordType.Name = 'Casual'];
        System.debug('ZZ '+stalls);
        System.debug('ZZ '+stalls.size());
        
        tmp = '<div class=\'floorplan\'>';
        For (integer i = 0; i <stalls.size(); i++){ 
            tmp += '<a class=\'room\' style=\' width:'+stalls.get(i).Width__c+'px; height:'+stalls.get(i).Height__c+
                'px; line-height:'+stalls.get(i).Line_Height__c+'px; top:'+stalls.get(i).Top__c+'px; left:'+stalls.get(i).Left__c+'px;\'>' +
                stalls.get(i).Name +'</a>' ;
        }
        
        tmp += '</div>';
        System.debug('TABLE '+tmp);
        return tmp;
    }
}